export type Taglia = "piccola" | "media" | "grande" | "gigante";
export type Energia = "bassa" | "media" | "alta";
export type Appartamento = "ottimo" | "medio" | "sconsigliato";
export type Bambini = "ottimo" | "buono" | "medio";
export type Pelo = "corto" | "medio" | "lungo";
export type Esperienza = "principiante" | "intermedio" | "esperto";

export interface RazzaFaq {
  q: string;
  a: string;
}

export interface Razza {
  slug: string;
  nome: string;
  taglia: Taglia;
  energia: Energia;
  appartamento: Appartamento;
  bambini: Bambini;
  pelo: Pelo;
  esperienzaMinima: Esperienza;
  costoMensile: number;
  descrizione: string;
  caratteristiche: string[];
  foto: string;
  magazineSlug?: string;
  // Dati anagrafici FCI (per scheda dettaglio)
  origine: string;
  pesoMinKg: number;
  pesoMaxKg: number;
  altezzaMinCm: number;
  altezzaMaxCm: number;
  vitaMediaMinAnni: number;
  vitaMediaMaxAnni: number;
  // Contenuti editoriali scheda
  storia: string;
  carattere: string;
  addestramento: string;
  salute: string;
  saluteProblemi: string[];
  alimentazione: string;
  toelettatura: string;
  idealePer: string[];
  nonAdattoA: string[];
  faq: RazzaFaq[];
}

export const RAZZE: Razza[] = [
  {
    slug: "labrador-retriever",
    nome: "Labrador Retriever",
    taglia: "grande",
    energia: "alta",
    appartamento: "medio",
    bambini: "ottimo",
    pelo: "corto",
    esperienzaMinima: "principiante",
    costoMensile: 150,
    descrizione: "Il cane da famiglia per eccellenza: affettuoso, socievole, instancabile.",
    caratteristiche: ["Ottimo con bambini", "Facile da addestrare", "Molto attivo"],
    foto: "https://images.unsplash.com/photo-1591160690555-5debfba289f0?w=800&q=80",
    origine: "Canada (Terranova)",
    pesoMinKg: 25, pesoMaxKg: 36, altezzaMinCm: 54, altezzaMaxCm: 62,
    vitaMediaMinAnni: 10, vitaMediaMaxAnni: 14,
    storia: "Il Labrador Retriever nasce a Terranova, in Canada, nell'800 come aiuto dei pescatori: recuperava le reti e i pesci sfuggiti. Fu poi perfezionato in Inghilterra dai nobili britannici, che lo apprezzarono per la dolcezza e l'intelligenza. Oggi e il cane piu diffuso al mondo, amato come animale da famiglia, cane guida per non vedenti e cane da assistenza.",
    carattere: "Il Labrador e l'incarnazione del cane socievole: adora le persone, gli altri cani, i bambini e persino i gatti. Ha un'energia esuberante nei primi anni che si smorza intorno ai 4-5 anni. Non e mai aggressivo, e un pessimo cane da guardia proprio perche saluterebbe anche il ladro. Ha bisogno di presenza umana costante: lasciato solo troppe ore diventa triste e puo sviluppare comportamenti distruttivi.",
    addestramento: "Fra i cani piu facili da addestrare al mondo. Impara rapidamente con il metodo positivo (rinforzo con cibo e coccole) ma attenzione: mangia tutto quello che vede, quindi e facile fargli prendere peso usando troppi premi. Ideale per la prima esperienza cinofila.",
    salute: "In generale robusto ma soggetto a problemi ereditari legati alla crescita rapida e alla genetica della razza.",
    saluteProblemi: ["Displasia dell'anca", "Displasia del gomito", "Obesita", "Problemi oculari (cataratta, PRA)"],
    alimentazione: "0.25-0.35 kg/giorno di crocchette di qualita per cani di taglia grande. Divide in 2 pasti. Attenzione rigorosa al peso: il Labrador e geneticamente predisposto all'obesita (40% degli esemplari) a causa di una mutazione del gene POMC.",
    toelettatura: "Pelo corto facile: una spazzolatura 1-2 volte a settimana, piu spesso durante la muta (primavera/autunno). Bagno solo quando e sporco. Non richiede toelettatura professionale.",
    idealePer: ["Famiglie con bambini", "Prima esperienza cinofila", "Case con giardino", "Sportivi e runner"],
    nonAdattoA: ["Chi sta fuori casa 10+ ore", "Appartamenti piccoli senza uscite", "Chi cerca un cane da guardia"],
    faq: [
      { q: "Quanto costa un Labrador cucciolo?", a: "Un cucciolo con pedigree costa tra 800 e 1.500 euro in Italia. Senza pedigree da privati 400-800 euro. Meglio pero adottare da rifugio: molti Labrador finiscono in canile perche sottovalutati nella gestione." },
      { q: "Labrador in appartamento: si o no?", a: "Si puo, ma solo se garantisci almeno 2 uscite lunghe al giorno (1h+1h) e attivita mentale. Senza movimento diventa distruttivo in casa." },
      { q: "Perche il Labrador ingrassa cosi facilmente?", a: "Il 40% dei Labrador ha una mutazione del gene POMC che regola l'appetito: sono geneticamente programmati per mangiare piu del necessario. Pesalo ogni 2 settimane." },
    ],
  },
  {
    slug: "golden-retriever",
    nome: "Golden Retriever",
    taglia: "grande",
    energia: "alta",
    appartamento: "medio",
    bambini: "ottimo",
    pelo: "lungo",
    esperienzaMinima: "principiante",
    costoMensile: 170,
    descrizione: "Dolce, paziente e intelligente. Adora la famiglia e le lunghe passeggiate.",
    caratteristiche: ["Tenero e paziente", "Adatto a famiglie", "Necessita toelettatura"],
    foto: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=800&q=80",
    origine: "Scozia",
    pesoMinKg: 25, pesoMaxKg: 34, altezzaMinCm: 51, altezzaMaxCm: 61,
    vitaMediaMinAnni: 10, vitaMediaMaxAnni: 12,
    storia: "Selezionato nel XIX secolo da Lord Tweedmouth in Scozia incrociando un retriever giallo con un Tweed Water Spaniel oggi estinto. Nato come cane da riporto nella caccia alle anatre sui laghi scozzesi, il Golden e diventato uno dei cani da compagnia piu amati del pianeta.",
    carattere: "Il Golden e famoso per essere gentile con tutti. Pazientissimo con i bambini (anche quelli invadenti), accogliente con gli ospiti, tollerante con altri animali. E sensibile alle emozioni umane: molti esemplari lavorano come cani di supporto emotivo. Meno eccitabile del Labrador ma con la stessa energia nei primi anni.",
    addestramento: "Come il Labrador, uno dei cani piu facili da educare al mondo. Impara per compiacere il padrone, non per ottenere cibo. Ottimo nell'obedience, agility, nose work e come cane da assistenza. Il metodo positivo e sempre la scelta giusta.",
    salute: "Meno longevo di altre razze di taglia grande. Attenzione al peso che puo peggiorare problemi articolari.",
    saluteProblemi: ["Displasia dell'anca", "Tumori (incidenza alta)", "Problemi cardiaci", "Problemi dermatologici"],
    alimentazione: "0.25-0.35 kg/giorno di crocchette premium, divise in 2 pasti. Controlla peso mensilmente.",
    toelettatura: "Pelo lungo folto con sottopelo denso: richiede spazzolatura profonda 3 volte a settimana e muta due volte l'anno molto abbondante. Non serve tosare (mai raso, rovina la termoregolazione). Bagno ogni 2-3 mesi.",
    idealePer: ["Famiglie con bambini piccoli", "Chi vuole un cane molto dolce", "Attivita sportive outdoor"],
    nonAdattoA: ["Chi non ha tempo per toelettatura", "Appartamento senza giardino", "Chi cerca cane da guardia"],
    faq: [
      { q: "Golden Retriever o Labrador: quale scegliere?", a: "Golden e un po' piu calmo e dolce, Labrador piu esuberante e facile da curare. Se hai bambini piccoli il Golden e piu paziente; se fai molto sport il Labrador ha piu resistenza." },
      { q: "Quanto pelo perde?", a: "Tantissimo, tutto l'anno, ma soprattutto in primavera e autunno. Conta di dover spazzolare 15-20 minuti 3 volte a settimana tutto l'anno." },
    ],
  },
  {
    slug: "pastore-tedesco",
    nome: "Pastore Tedesco",
    taglia: "grande",
    energia: "alta",
    appartamento: "sconsigliato",
    bambini: "buono",
    pelo: "medio",
    esperienzaMinima: "intermedio",
    costoMensile: 160,
    descrizione: "Intelligente, leale, protettivo. Richiede spazio e un proprietario presente.",
    caratteristiche: ["Molto intelligente", "Guardiano naturale", "Necessita spazio"],
    foto: "https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=800&q=80",
    origine: "Germania",
    pesoMinKg: 22, pesoMaxKg: 40, altezzaMinCm: 55, altezzaMaxCm: 65,
    vitaMediaMinAnni: 9, vitaMediaMaxAnni: 13,
    storia: "Selezionato nel 1899 dal capitano tedesco Max von Stephanitz come cane da pastore polivalente. Divento rapidamente il cane da lavoro per eccellenza: polizia, esercito, soccorso, assistenza. E forse la razza piu versatile mai creata.",
    carattere: "Fedele fino all'ultimo respiro, estremamente intelligente (3o posto mondiale per QI canino secondo Stanley Coren), protettivo del suo branco umano. Puo essere diffidente verso gli estranei ma non aggressivo se ben socializzato da cucciolo. E un cane sensibile che soffre la solitudine e i cambiamenti bruschi.",
    addestramento: "Impara comandi nuovi in 5 ripetizioni o meno. Richiede un padrone coerente e fermo (non duro). Socializzazione precoce fondamentale: senza di essa puo diventare diffidente o reattivo. Ideale per sport cinofili (IPO, obedience, agility).",
    salute: "Soggetto a patologie ereditarie selezionate malamente per l'estetica (linea da show americana).",
    saluteProblemi: ["Displasia dell'anca", "Mielopatia degenerativa", "Torsione gastrica", "Problemi digestivi"],
    alimentazione: "0.3-0.5 kg/giorno divisi in 2-3 pasti per evitare torsione gastrica (mai 1 pasto unico). Privilegia crocchette per taglia grande con glucosamina per le articolazioni.",
    toelettatura: "Pelo medio doppio: spazzola 2-3 volte a settimana, ogni giorno durante le mute. Non tosare mai.",
    idealePer: ["Proprietari attivi con esperienza cinofila", "Chi ha tempo da dedicare", "Case con giardino recintato", "Sport cinofili"],
    nonAdattoA: ["Prima esperienza cinofila", "Appartamento senza uscite", "Chi sta fuori tutto il giorno", "Famiglie con bambini molto piccoli"],
    faq: [
      { q: "Il Pastore Tedesco e un cane pericoloso?", a: "No. Non e in nessuna lista di razze pericolose in Italia. E un cane equilibrato se socializzato da cucciolo. I problemi comportamentali derivano quasi sempre da addestramento sbagliato o isolamento." },
      { q: "Linea da lavoro o da show: quale scegliere?", a: "Linea da lavoro (tedesca DDR o check) e piu sana fisicamente e mentalmente. La linea da show americana/inglese ha problemi di schiena e articolazioni per la selezione estetica." },
    ],
  },
  {
    slug: "border-collie",
    nome: "Border Collie",
    taglia: "media",
    energia: "alta",
    appartamento: "sconsigliato",
    bambini: "buono",
    pelo: "medio",
    esperienzaMinima: "esperto",
    costoMensile: 140,
    descrizione: "Il cane piu intelligente del mondo. Ha bisogno di tanto movimento e stimoli mentali.",
    caratteristiche: ["Super intelligente", "Ideale per sport cinofili", "Non adatto a sedentari"],
    foto: "https://images.unsplash.com/photo-1503256207526-0d5d80fa2f47?w=800&q=80",
    origine: "Confine Scozia-Inghilterra",
    pesoMinKg: 12, pesoMaxKg: 20, altezzaMinCm: 46, altezzaMaxCm: 56,
    vitaMediaMinAnni: 12, vitaMediaMaxAnni: 15,
    storia: "Nato sui confini (borders) tra Scozia e Inghilterra come cane da conduzione delle pecore. Selezionato esclusivamente per il lavoro, non per l'estetica. Considerato dalla ricerca scientifica (Stanley Coren, University of British Columbia) come la razza piu intelligente al mondo.",
    carattere: "Intensita totale. Il Border Collie non vive, lavora. Osserva ogni movimento, anticipa ogni gesto, cerca costantemente qualcosa da fare. Se non gli dai un lavoro, se lo inventa (spesso male). E affettuoso ma non appiccicoso, legato al padrone ma non dipendente.",
    addestramento: "Il cane piu addestrabile al mondo. Impara un comando nuovo in 1-3 ripetizioni. Eccelle in ogni disciplina cinofila: obedience, agility, disc dog, conduzione ovini. Ma attenzione: senza stimolazione mentale E fisica quotidiana (minimo 2h totali) sviluppa comportamenti ossessivi.",
    salute: "Generalmente robusto, ma soggetto ad alcune patologie ereditarie specifiche.",
    saluteProblemi: ["Collie Eye Anomaly (CEA)", "Epilessia", "MDR1 (sensibilita a farmaci)", "Displasia dell'anca"],
    alimentazione: "0.2-0.3 kg/giorno di crocchette per taglia media ad alto contenuto energetico. Sport dog food se pratica agility intensiva.",
    toelettatura: "Pelo medio-lungo con sottopelo: spazzolatura 2-3 volte a settimana.",
    idealePer: ["Sportivi veri", "Agility, disc dog, conduzione", "Educatori cinofili", "Chi vive in campagna con animali"],
    nonAdattoA: ["Appartamento senza uscite", "Famiglie sedentarie", "Chi cerca un cane da coccolare sul divano", "Prima esperienza"],
    faq: [
      { q: "Quanto movimento serve al Border Collie?", a: "Minimo 2 ore al giorno di movimento fisico + 1 ora di attivita mentale (giochi di nose work, pet olfattivo, problem solving). Non bastano 3 passeggiate banali." },
      { q: "Il Border Collie puo vivere in appartamento?", a: "Fisicamente si (e piccolo-medio), mentalmente no se non hai tempo da dedicargli come fosse un atleta. La maggior parte dei Border Collie in citta e infelice." },
    ],
  },
  {
    slug: "jack-russell-terrier",
    nome: "Jack Russell Terrier",
    taglia: "piccola",
    energia: "alta",
    appartamento: "ottimo",
    bambini: "buono",
    pelo: "corto",
    esperienzaMinima: "intermedio",
    costoMensile: 90,
    descrizione: "Piccolo ma con l'energia di un grande cane. Vivace, curioso, coraggioso.",
    caratteristiche: ["Esplosivo di energia", "Ottimo per attivita", "Testardo"],
    foto: "https://images.unsplash.com/photo-1597633244018-0201d0158aab?w=800&q=80",
    origine: "Inghilterra",
    pesoMinKg: 5, pesoMaxKg: 8, altezzaMinCm: 25, altezzaMaxCm: 30,
    vitaMediaMinAnni: 13, vitaMediaMaxAnni: 16,
    storia: "Selezionato nell'800 dal reverendo John Russell per la caccia alla volpe: doveva stanarla dalla tana. Piccolo ma coraggioso, tenace e instancabile. Tra i cani piu longevi.",
    carattere: "Dentro un Jack Russell c'e un Pastore Tedesco di 40 kg. Non si lascia intimidire da nulla: sfidera cani 5 volte piu grandi senza battere ciglio. E intelligente, testardo, esuberante, divertente. Non e un cane da poltrona: scava, salta, rincorre tutto quello che si muove.",
    addestramento: "Non difficile ma impegnativo: capisce tutto subito ma decide lui se obbedire. Metodo positivo sempre, coerenza assoluta, mai permettere eccezioni ('oggi sul divano, domani no' non funziona).",
    salute: "Razza mediamente robusta e longeva.",
    saluteProblemi: ["Lussazione della rotula", "Problemi oculari (cataratta)", "Sordita", "Sindrome di Cushing in eta avanzata"],
    alimentazione: "0.1-0.15 kg/giorno, 2 pasti. Facili a ingrassare se poco movimento.",
    toelettatura: "Pelo corto o ruvido: spazzola 1 volta a settimana. La varieta a pelo ruvido richiede stripping 2 volte l'anno.",
    idealePer: ["Sportivi", "Famiglie attive", "Casa con giardino recintato (ma scappa se trova un pertugio!)"],
    nonAdattoA: ["Famiglie sedentarie", "Case con conigli o porcellini d'India", "Chi vuole un cane calmo"],
    faq: [
      { q: "Il Jack Russell va bene con i bambini?", a: "Si, ma con bambini sopra i 6-7 anni che sanno rispettare il cane. Con i piu piccoli puo essere intollerante ai comportamenti bruschi." },
      { q: "Quanto dorme un Jack Russell adulto?", a: "12-14 ore al giorno come tutti i cani. Ma le 10-12 ore sveglie sono di attivita intensa: preparati." },
    ],
  },
  {
    slug: "chihuahua",
    nome: "Chihuahua",
    taglia: "piccola",
    energia: "media",
    appartamento: "ottimo",
    bambini: "medio",
    pelo: "corto",
    esperienzaMinima: "principiante",
    costoMensile: 70,
    descrizione: "Il piu piccolo del mondo. Fedele al padrone, ideale per la vita in citta.",
    caratteristiche: ["Perfetto in appartamento", "Poco impegnativo", "Molto legato al padrone"],
    foto: "https://images.unsplash.com/photo-1605568427561-40dd23c2acea?w=800&q=80",
    origine: "Messico",
    pesoMinKg: 1, pesoMaxKg: 3, altezzaMinCm: 15, altezzaMaxCm: 23,
    vitaMediaMinAnni: 14, vitaMediaMaxAnni: 18,
    storia: "Il cane piu antico delle Americhe: i suoi antenati (Techichi) erano venerati dagli Aztechi. Prende nome dallo stato messicano di Chihuahua dove fu riscoperto nell'800. E la razza ufficialmente piu piccola del mondo per standard FCI.",
    carattere: "Molto legato al suo padrone, tendenzialmente monoprotettivo: sceglie una persona e quella diventa il suo mondo. Coraggioso oltre la sua taglia (sfida cani grandi), diffidente con estranei, rumoroso. Non e un giocattolo: ha bisogno di educazione come ogni altro cane, altrimenti sviluppa la 'Small Dog Syndrome' (ansia, aggressivita, capricci).",
    addestramento: "Intelligente ma puo essere testardo. La difficolta principale e che i padroni tendono a perdonargli tutto perche 'e piccolo', creando un cane mal educato. Stessa coerenza che useresti con un grande cane.",
    salute: "Razza molto longeva ma delicata fisicamente.",
    saluteProblemi: ["Lussazione della rotula", "Fontanella aperta (molera)", "Ipoglicemia nei cuccioli", "Problemi cardiaci", "Problemi dentali"],
    alimentazione: "50-80 g/giorno di crocchette per cani toy, 3 pasti (cuccioli 4 pasti per evitare ipoglicemia).",
    toelettatura: "Pelo corto: spazzola 1 volta a settimana. Attenzione al freddo: a temperature sotto i 10C indossa un cappottino, non e snobismo.",
    idealePer: ["Vita in appartamento", "Anziani e single", "Chi vuole un cane da compagnia vero", "Chi lavora da casa"],
    nonAdattoA: ["Famiglie con bambini piccoli (fragilita fisica)", "Chi vuole un cane sportivo", "Chi viaggia sempre"],
    faq: [
      { q: "Il Chihuahua e un cane vero o un giocattolo?", a: "Un cane vero, con bisogni veri (passeggiate, socializzazione, educazione). Trattarlo come un giocattolo crea ansia e comportamenti problematici." },
      { q: "Quanto costa un Chihuahua?", a: "Cucciolo con pedigree 900-1800 euro. Attenzione alle offerte troppo basse: spesso sono cuccioli da allevamenti intensivi o importati illegalmente." },
    ],
  },
  {
    slug: "bulldog-francese",
    nome: "Bulldog Francese",
    taglia: "piccola",
    energia: "bassa",
    appartamento: "ottimo",
    bambini: "ottimo",
    pelo: "corto",
    esperienzaMinima: "principiante",
    costoMensile: 110,
    descrizione: "Divertente, affettuoso e adatto alla vita in appartamento. Poche passeggiate.",
    caratteristiche: ["Pigro e coccolone", "Perfetto in citta", "Attenzione al caldo"],
    foto: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=800&q=80",
    origine: "Francia (ma origini inglesi)",
    pesoMinKg: 8, pesoMaxKg: 14, altezzaMinCm: 27, altezzaMaxCm: 35,
    vitaMediaMinAnni: 10, vitaMediaMaxAnni: 12,
    storia: "Nato nell'800 come piccolo bulldog inglese portato in Francia dagli emigranti merlettai di Nottingham, incrociato con terrier locali. Divento presto cane da compagnia delle prostitute parigine, poi dell'aristocrazia. Oggi e una delle razze piu popolari al mondo.",
    carattere: "Il comico della famiglia. Divertente, espressivo, affettuoso al limite del dipendente. Ama coccolare sul divano e dormire tra i piedi dei padroni. Relativamente tranquillo in casa, ha bisogno di poche passeggiate (30-45 minuti totali al giorno). E ottimo con i bambini e tollerante con gli estranei.",
    addestramento: "Intelligente ma testardo, tipicamente francese. Non eccelle nell'obedience ma impara i comandi base senza problemi. Metodo positivo e pazienza.",
    salute: "Purtroppo una delle razze con piu problemi di salute, quasi tutti legati alla conformazione brachicefala (muso schiacciato).",
    saluteProblemi: ["Sindrome brachicefalica (difficolta respirazione)", "Problemi colonna vertebrale", "Dermatiti pieghe", "Intolleranza al caldo", "Problemi parto (solo cesareo)"],
    alimentazione: "0.1-0.15 kg/giorno, 2 pasti. Facili a ingrassare per scarso movimento.",
    toelettatura: "Pelo corto: 1 spazzolatura a settimana. Pulizia quotidiana delle pieghe del muso per evitare dermatiti batteriche.",
    idealePer: ["Vita in appartamento", "Famiglie con bambini", "Chi vuole un cane poco impegnativo", "Anziani"],
    nonAdattoA: ["Chi vive in zone molto calde", "Sportivi che vogliono un compagno di corsa", "Chi cerca un cane da guardia"],
    faq: [
      { q: "Il Bulldog Francese soffre sempre il caldo?", a: "Si, per via del muso corto non riesce a dissipare bene il calore. A 25C e gia in difficolta, a 30C puo andare in colpo di calore fatale. In estate porta sempre acqua." },
      { q: "Perche costa cosi tanto?", a: "1200-2500 euro perche nascono solo con cesareo programmato (bacino stretto) e le cucciolate sono piccole (3-5 cuccioli). E una delle razze piu costose da allevare." },
    ],
  },
  {
    slug: "beagle",
    nome: "Beagle",
    taglia: "media",
    energia: "alta",
    appartamento: "medio",
    bambini: "ottimo",
    pelo: "corto",
    esperienzaMinima: "intermedio",
    costoMensile: 120,
    descrizione: "Socievole, curioso, vorace. Perfetto in famiglia ma segue sempre il naso.",
    caratteristiche: ["Allegro e socievole", "Adora i bambini", "Tende a fuggire"],
    foto: "https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=800&q=80",
    origine: "Inghilterra",
    pesoMinKg: 9, pesoMaxKg: 15, altezzaMinCm: 33, altezzaMaxCm: 40,
    vitaMediaMinAnni: 12, vitaMediaMaxAnni: 15,
    storia: "Razza inglese selezionata dal XV secolo per la caccia alla lepre in muta. E un segugio con olfatto incredibile (secondo solo al Bloodhound). Divenne famoso negli anni 60 anche per essere Snoopy dei Peanuts.",
    carattere: "Un cane felice di natura. Socievole con tutto e tutti, ama i bambini, gli altri cani, gli estranei. E testardo quando segue una pista olfattiva: diventa sordo a tutti i richiami. Vocale (ulula e abbaia), cosa da considerare se vivi in condominio.",
    addestramento: "Difficile nel richiamo e nelle distrazioni olfattive. Facile nel resto. Non aspettarti un obedient dog: e un segugio geneticamente programmato a seguire il naso.",
    salute: "Razza robusta ma tendente all'obesita e a problemi specifici.",
    saluteProblemi: ["Obesita", "Epilessia idiopatica", "Problemi oculari", "Ipotiroidismo", "Otiti (orecchie lunghe)"],
    alimentazione: "0.2-0.3 kg/giorno, 2 pasti. Mangerebbe qualsiasi cosa: chiudi il cibo a chiave.",
    toelettatura: "Pelo corto: spazzola 1 volta a settimana. Pulisci le orecchie ogni settimana per evitare otiti.",
    idealePer: ["Famiglie con bambini", "Chi ha un altro cane (ama la compagnia)", "Casa con giardino recintato"],
    nonAdattoA: ["Appartamenti con vicini sensibili al rumore", "Chi vuole un cane sciolto al parco", "Chi non ha pazienza"],
    faq: [
      { q: "Il Beagle abbaia molto?", a: "Si, piu di altre razze. Ulula quando e solo, abbaia quando sente qualcosa interessante. Considera i vicini prima di prenderlo in condominio." },
      { q: "Posso lasciare il Beagle sciolto al parco?", a: "No, mai. Al primo odore interessante sparisce. Usa un guinzaglio lungo o un'area recintata." },
    ],
  },
  {
    slug: "cavalier-king-charles",
    nome: "Cavalier King Charles",
    taglia: "piccola",
    energia: "media",
    appartamento: "ottimo",
    bambini: "ottimo",
    pelo: "lungo",
    esperienzaMinima: "principiante",
    costoMensile: 120,
    descrizione: "Dolcissimo cane da compagnia, affettuoso con tutti, ideale per la famiglia.",
    caratteristiche: ["Super coccolone", "Ottimo con bambini", "Richiede compagnia"],
    foto: "https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=800&q=80",
    origine: "Inghilterra",
    pesoMinKg: 5, pesoMaxKg: 8, altezzaMinCm: 30, altezzaMaxCm: 33,
    vitaMediaMinAnni: 9, vitaMediaMaxAnni: 14,
    storia: "Selezionato in Inghilterra dal XVII secolo come cane da compagnia dell'aristocrazia. Re Carlo II lo amava al punto che ne era sempre accompagnato: da qui il nome. Oggi e il cane da compagnia per eccellenza.",
    carattere: "La dolcezza fatta cane. Non conosce aggressivita, adora tutto quello che si muove, bambini inclusi. E dipendente affettivamente: lasciato solo soffre molto. Perfetto per chi vuole un 'cane velcro' sempre tra i piedi.",
    addestramento: "Facile e piacevole. Non eccelle nello sport ma impara i comandi base senza problemi.",
    salute: "Razza purtroppo con gravi problemi genetici selezionati dai breeder per l'estetica.",
    saluteProblemi: ["Malattia valvolare cardiaca (molto comune)", "Siringomielia", "Problemi oculari", "Displasia dell'anca"],
    alimentazione: "0.1-0.15 kg/giorno di crocchette premium, 2 pasti.",
    toelettatura: "Pelo lungo setoso: spazzola ogni giorno per evitare nodi, soprattutto dietro le orecchie. Toelettatura professionale ogni 2-3 mesi.",
    idealePer: ["Famiglie con bambini", "Anziani", "Chi vive in appartamento", "Chi cerca il perfetto cane da compagnia"],
    nonAdattoA: ["Chi sta fuori 10 ore", "Chi cerca un cane sportivo", "Chi non tollera tanta dipendenza affettiva"],
    faq: [
      { q: "Il Cavalier King soffre di cuore davvero cosi tanto?", a: "Si, purtroppo. Il 50% ha una MVD (malattia valvolare) entro i 5 anni, il 100% entro i 10. Scegli solo allevatori che testano i riproduttori." },
      { q: "Perde tanto pelo?", a: "Si, abbastanza. Non e una razza ipoallergenica." },
    ],
  },
  {
    slug: "bassotto",
    nome: "Bassotto",
    taglia: "piccola",
    energia: "media",
    appartamento: "ottimo",
    bambini: "buono",
    pelo: "corto",
    esperienzaMinima: "intermedio",
    costoMensile: 90,
    descrizione: "Coraggioso, testardo, affettuoso. Perfetto in appartamento, ama scavare.",
    caratteristiche: ["Carattere forte", "Ideale in citta", "Attenzione alla schiena"],
    foto: "https://images.unsplash.com/photo-1612536057832-2ff7ead58194?w=800&q=80",
    origine: "Germania",
    pesoMinKg: 4, pesoMaxKg: 9, altezzaMinCm: 20, altezzaMaxCm: 27,
    vitaMediaMinAnni: 12, vitaMediaMaxAnni: 16,
    storia: "Nato in Germania nel 1700 come cane da caccia al tasso ('dachs' in tedesco significa tasso, 'hund' cane). Il suo corpo allungato gli permetteva di entrare nelle tane. Oggi e prevalentemente cane da compagnia.",
    carattere: "Dentro un Bassotto c'e un cane 10 volte piu grande. Coraggioso, testardo, vocale. Molto legato al padrone ma indipendente nelle decisioni. Puo essere diffidente con estranei e altri cani.",
    addestramento: "Testardo come solo i segugi tedeschi sanno esserlo. Ripetizioni, pazienza, metodo positivo. Non aspettarti l'obedient dog.",
    salute: "La forma allungata causa problemi specifici alla colonna vertebrale.",
    saluteProblemi: ["IVDD (ernia del disco) - comune", "Obesita (peggiora IVDD)", "Problemi dentali", "Epilessia"],
    alimentazione: "Porzioni controllate: 0.1 kg/giorno. L'obesita e un killer in questa razza.",
    toelettatura: "Dipende dalla varieta: pelo corto 1 volta a settimana, pelo duro stripping 2 volte/anno, pelo lungo spazzola quotidiana.",
    idealePer: ["Appartamento", "Chi vuole un cane con carattere", "Famiglie con bambini sopra i 6 anni"],
    nonAdattoA: ["Case con tante scale (rischio schiena)", "Chi vuole un cane obbediente", "Chi ha altri piccoli animali (istinto di caccia)"],
    faq: [
      { q: "Posso far fare le scale al mio Bassotto?", a: "Il meno possibile. Le scale (salire e scendere) stressano la colonna vertebrale e sono la prima causa di ernie. In casa con scale usa una rampa." },
      { q: "Il Bassotto va bene con i gatti?", a: "Dipende dal cucciolo e dalla socializzazione. Molti Bassotti vivono benissimo con gatti se cresciuti insieme." },
    ],
  },
  {
    slug: "boxer",
    nome: "Boxer",
    taglia: "grande",
    energia: "alta",
    appartamento: "medio",
    bambini: "ottimo",
    pelo: "corto",
    esperienzaMinima: "intermedio",
    costoMensile: 150,
    descrizione: "Giocherellone eterno, fedele e protettivo. Ottimo cane da famiglia attiva.",
    caratteristiche: ["Eternamente cucciolo", "Protettivo", "Molto giocoso"],
    foto: "https://images.unsplash.com/photo-1568572933382-74d440642117?w=800&q=80",
    origine: "Germania",
    pesoMinKg: 25, pesoMaxKg: 32, altezzaMinCm: 53, altezzaMaxCm: 63,
    vitaMediaMinAnni: 9, vitaMediaMaxAnni: 12,
    storia: "Selezionato in Germania alla fine dell'800 incrociando il Bullenbeisser (antico molosso) con il Bulldog inglese. Nato come cane da lavoro e guardia, divento presto un amato cane da famiglia.",
    carattere: "Il Boxer non diventa mai adulto dentro. A 10 anni gioca come un cucciolo. E super legato alla famiglia, pazientissimo con i bambini, diffidente con estranei ma non aggressivo. Energia altissima nei primi 4-5 anni.",
    addestramento: "Medio difficile. Buffone ma intelligente, impara rapidamente ma spesso preferisce fare il matto. Metodo positivo rigoroso, socializzazione precoce fondamentale.",
    salute: "Razza con grave incidenza tumorale e patologie cardiache.",
    saluteProblemi: ["Tumori (incidenza molto alta)", "Cardiomiopatia dilatativa", "Displasia dell'anca", "Ipotiroidismo"],
    alimentazione: "0.3-0.4 kg/giorno, 2-3 pasti. Tendenza a rigurgito se mangia troppo velocemente.",
    toelettatura: "Pelo corto facile: 1 spazzolatura a settimana.",
    idealePer: ["Famiglie con bambini", "Chi fa sport", "Case con giardino"],
    nonAdattoA: ["Chi cerca un cane calmo", "Appartamento piccolo senza uscite", "Chi non tollera le sbavature"],
    faq: [
      { q: "Il Boxer sbava molto?", a: "Abbastanza, specialmente dopo aver bevuto e durante i giochi. Non come un San Bernardo ma ci sara sempre qualche goccia sul pavimento." },
      { q: "Il Boxer e aggressivo?", a: "No, se ben socializzato. E protettivo della famiglia ma non reattivo. Abbaia agli estranei ma raramente morde." },
    ],
  },
  {
    slug: "rottweiler",
    nome: "Rottweiler",
    taglia: "grande",
    energia: "media",
    appartamento: "sconsigliato",
    bambini: "buono",
    pelo: "corto",
    esperienzaMinima: "esperto",
    costoMensile: 180,
    descrizione: "Forte, leale, protettivo. Richiede un proprietario esperto e addestramento.",
    caratteristiche: ["Molto protettivo", "Richiede esperienza", "Fedele alla famiglia"],
    foto: "https://images.unsplash.com/photo-1567752881298-894bb81f9379?w=800&q=80",
    origine: "Germania (Rottweil)",
    pesoMinKg: 35, pesoMaxKg: 60, altezzaMinCm: 56, altezzaMaxCm: 68,
    vitaMediaMinAnni: 8, vitaMediaMaxAnni: 11,
    storia: "Discende dai cani dei legionari romani usati per guidare il bestiame. Nel Medioevo fu selezionato nella citta tedesca di Rottweil come cane da macellaio (trasporto di carne e soldi). Oggi e usato come cane da polizia, guardia e compagnia.",
    carattere: "Il Rottweiler e calmo, sicuro di se, territoriale ma non aggressivo. E fedele fino al limite: se attaccano la sua famiglia non si tira indietro. Socializzato bene e un cane equilibrato con tutti. Non e un cane per principianti per la stazza e la forza.",
    addestramento: "Impara facilmente ma richiede un padrone esperto, coerente e fermo (mai duro). Socializzazione precoce e obbligatoria. Sport cinofili come IPO sono una buona valvola di sfogo.",
    salute: "Aspettativa di vita piu bassa della media canina per via di patologie gravi.",
    saluteProblemi: ["Tumori (osteosarcoma)", "Displasia dell'anca e del gomito", "Problemi cardiaci", "Parvovirus in cuccioli"],
    alimentazione: "0.4-0.6 kg/giorno, 2-3 pasti per evitare torsione gastrica.",
    toelettatura: "Pelo corto: 1-2 spazzolature a settimana.",
    idealePer: ["Padroni esperti", "Chi cerca un cane da guardia", "Case con giardino recintato", "Chi ha tempo da dedicare"],
    nonAdattoA: ["Prima esperienza cinofila", "Famiglie con bambini molto piccoli", "Appartamento"],
    faq: [
      { q: "Il Rottweiler e legalmente pericoloso in Italia?", a: "No. In Italia non esiste una lista di razze pericolose dal 2009 (ordinanza Martini abrogata). Il Rottweiler e un cane legale ovunque, ma il proprietario ha obblighi di responsabilita civile." },
      { q: "Quanto spazio serve per un Rottweiler?", a: "Ideale casa con giardino recintato. In appartamento puo adattarsi ma servono minimo 2 lunghe passeggiate al giorno + attivita." },
    ],
  },
  {
    slug: "shih-tzu",
    nome: "Shih Tzu",
    taglia: "piccola",
    energia: "bassa",
    appartamento: "ottimo",
    bambini: "ottimo",
    pelo: "lungo",
    esperienzaMinima: "principiante",
    costoMensile: 130,
    descrizione: "Piccolo, elegante, affettuoso. Ideale per chi cerca un compagno tranquillo.",
    caratteristiche: ["Tranquillo e dolce", "Perfetto in appartamento", "Molta toelettatura"],
    foto: "https://images.unsplash.com/photo-1604951589523-7e5e7b7f0dd9?w=800&q=80",
    origine: "Cina/Tibet",
    pesoMinKg: 4, pesoMaxKg: 7, altezzaMinCm: 20, altezzaMaxCm: 28,
    vitaMediaMinAnni: 10, vitaMediaMaxAnni: 16,
    storia: "Antichissima razza tibetana poi sviluppata nella corte imperiale cinese come cane da compagnia della nobilta. 'Shih Tzu' significa 'cane leone'. Rimase in Cina fino ai primi del '900 quando arrivo in Europa.",
    carattere: "Calmo, equilibrato, dolce. Adora le coccole ma non e dipendente. Va d'accordo con tutti: bambini, altri cani, gatti. Non e un cane da sport: ama le passeggiate brevi e dormire sul divano. Ideale per anziani e vita sedentaria.",
    addestramento: "Facile nei comandi base ma puo essere testardo nella toilette. Metodo positivo sempre.",
    salute: "Razza longeva ma con problemi legati alla conformazione.",
    saluteProblemi: ["Problemi oculari (occhi sporgenti)", "Respirazione brachicefala", "Problemi dentali", "Allergie cutanee"],
    alimentazione: "80-120 g/giorno, 2 pasti.",
    toelettatura: "Pelo lungo folto che arriva a terra: spazzola ogni giorno, bagno ogni 2-3 settimane, tosatura professionale ogni 2 mesi. Molti proprietari lo tengono corto per semplicita.",
    idealePer: ["Vita in appartamento", "Anziani e famiglie calme", "Chi vuole un cane che si adatta a tutto"],
    nonAdattoA: ["Chi non ha tempo per toelettatura", "Sportivi", "Zone molto calde"],
    faq: [
      { q: "Shih Tzu e ipoallergenico?", a: "Quasi. Non esiste un cane 100% ipoallergenico ma lo Shih Tzu perde pochissimo pelo e rilascia meno allergeni di altre razze." },
      { q: "Quanto costa tenere lo Shih Tzu dal toelettatore?", a: "Mediamente 40-60 euro a seduta, ogni 6-8 settimane. Molti proprietari imparano a farlo da soli." },
    ],
  },
  {
    slug: "maltese",
    nome: "Maltese",
    taglia: "piccola",
    energia: "bassa",
    appartamento: "ottimo",
    bambini: "buono",
    pelo: "lungo",
    esperienzaMinima: "principiante",
    costoMensile: 120,
    descrizione: "Piccolo, bianco, coccolone. Ideale per la vita in appartamento.",
    caratteristiche: ["Mantello bianco lungo", "Molto affettuoso", "Poco impegnativo"],
    foto: "https://images.unsplash.com/photo-1583512603805-3cc6b41f3edb?w=800&q=80",
    origine: "Italia (zona mediterranea)",
    pesoMinKg: 3, pesoMaxKg: 4, altezzaMinCm: 20, altezzaMaxCm: 25,
    vitaMediaMinAnni: 12, vitaMediaMaxAnni: 15,
    storia: "Razza antichissima del Mediterraneo (origini disputate tra Malta, Sicilia, Egitto). Era il cane da compagnia delle dame romane e rinascimentali. Rappresentato in molti quadri di Tiziano, Goya, Raffaello.",
    carattere: "Dolce, giocoso, legato al padrone. Allegro ma non esagerato. Va bene con bambini rispettosi e altri animali. Tipico cane da compagnia che ama le coccole ma anche piccole passeggiate.",
    addestramento: "Intelligente, impara facilmente se motivato con cibo o giochi. Pu diventare capriccioso se viziato.",
    salute: "Razza longeva con pochi problemi.",
    saluteProblemi: ["Problemi dentali", "Lussazione rotula", "Ipoglicemia in cuccioli", "Sindrome del cane bianco"],
    alimentazione: "60-100 g/giorno, 2 pasti.",
    toelettatura: "Pelo lungo bianco serico: spazzola ogni giorno per evitare nodi. Bagno ogni 2 settimane. Molti lo tengono corto.",
    idealePer: ["Vita urbana in appartamento", "Famiglie con bambini grandi", "Anziani"],
    nonAdattoA: ["Chi non ha tempo per toelettatura", "Chi cerca un cane sportivo"],
    faq: [
      { q: "Il Maltese perde pelo?", a: "Pochissimo. E considerato una delle razze piu adatte ad allergici." },
      { q: "Il pelo del Maltese si sporca facilmente?", a: "Si, il bianco mostra tutto. Serve bagno frequente e pulizia quotidiana del muso (lacrimazione)." },
    ],
  },
  {
    slug: "barboncino",
    nome: "Barboncino",
    taglia: "media",
    energia: "media",
    appartamento: "ottimo",
    bambini: "ottimo",
    pelo: "lungo",
    esperienzaMinima: "principiante",
    costoMensile: 140,
    descrizione: "Intelligente, anallergico, elegante. Disponibile in tutte le taglie.",
    caratteristiche: ["Anallergico", "Molto intelligente", "Richiede toelettatura"],
    foto: "https://images.unsplash.com/photo-1616148195041-c7d4a55ed21d?w=800&q=80",
    origine: "Francia/Germania",
    pesoMinKg: 3, pesoMaxKg: 28, altezzaMinCm: 25, altezzaMaxCm: 60,
    vitaMediaMinAnni: 12, vitaMediaMaxAnni: 16,
    storia: "Originariamente cane da riporto per anatre in Germania (il nome tedesco 'Pudel' viene da 'pudeln', sguazzare). Adottato dalla corte francese nel '700, divento simbolo di eleganza. Disponibile in 4 taglie (toy, nano, medio, grande).",
    carattere: "Considerato la seconda razza piu intelligente al mondo (dopo il Border Collie). Vivace, elegante, sensibile. Ottimo con bambini, allegro senza essere invadente. Taglia toy e nano sono piu territoriali, medio e grande piu equilibrati.",
    addestramento: "Facilissimo: impara per piacere al padrone, eccelle in obedience, agility, circus dog, nose work. Ideale anche per prima esperienza.",
    salute: "Razza longeva ma con alcuni problemi specifici.",
    saluteProblemi: ["Displasia anca (taglie grandi)", "Problemi oculari", "Addison", "Epilessia", "Lussazione rotula (toy/nano)"],
    alimentazione: "Varia dalla taglia: toy 60g, grande 0.3 kg. Sempre alta qualita.",
    toelettatura: "Pelo riccio che non cade ma cresce: toelettatura professionale obbligatoria ogni 6-8 settimane. Costo mensile: 40-80 euro.",
    idealePer: ["Allergici", "Famiglie", "Vita in appartamento o campagna", "Chi vuole un cane intelligente"],
    nonAdattoA: ["Chi ha budget limitato per toelettatura", "Chi non tollera un cane sensibile"],
    faq: [
      { q: "Il Barboncino e davvero ipoallergenico?", a: "E una delle razze piu adatte ad allergici perche non perde pelo. Ma non esiste il cane 100% ipoallergenico: fai prima un test con un barboncino prima di prenderlo." },
      { q: "Quale taglia di Barboncino scegliere?", a: "Toy/nano per vita in appartamento, medio per famiglia con bambini, grande per chi vuole un cane sportivo. Il carattere e lo stesso per tutte le taglie." },
    ],
  },
  {
    slug: "setter-inglese",
    nome: "Setter Inglese",
    taglia: "grande",
    energia: "alta",
    appartamento: "sconsigliato",
    bambini: "ottimo",
    pelo: "lungo",
    esperienzaMinima: "intermedio",
    costoMensile: 160,
    descrizione: "Elegante, dolce, sportivo. Ha bisogno di molto spazio e movimento.",
    caratteristiche: ["Ottimo da caccia e compagnia", "Molto affettuoso", "Richiede spazio"],
    foto: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=800&q=80",
    origine: "Inghilterra",
    pesoMinKg: 20, pesoMaxKg: 36, altezzaMinCm: 61, altezzaMaxCm: 69,
    vitaMediaMinAnni: 11, vitaMediaMaxAnni: 15,
    storia: "Selezionato nell'800 da Edward Laverack come cane da ferma per la caccia. Prende il nome dalla posizione 'di ferma' assunta davanti alla preda: si accovaccia (setter significa 'chi si siede'). Oggi e amato come cane da famiglia attiva.",
    carattere: "Dolce, affettuoso, elegante. Nervoso e sensibile: non tollera voci alte o punizioni. Adora la famiglia e i bambini. Ha un'energia pari al Border Collie: se non la scarica, impazzisce.",
    addestramento: "Intelligente ma sensibile. Solo metodo positivo, mai alzare la voce. Non e ideale come primo cane perche richiede movimento e gestione intelligente dell'energia.",
    salute: "Razza robusta, discreta longevita per una taglia grande.",
    saluteProblemi: ["Displasia dell'anca", "Torsione gastrica", "Ipotiroidismo", "Otiti"],
    alimentazione: "0.3-0.4 kg/giorno, 2-3 pasti.",
    toelettatura: "Pelo lungo setoso: spazzola 3 volte a settimana, controllo quotidiano per frangini. Pulizia orecchie settimanale.",
    idealePer: ["Sportivi e cacciatori", "Famiglie attive", "Case in campagna"],
    nonAdattoA: ["Appartamento", "Famiglie sedentarie", "Chi non sopporta il pelo sul divano"],
    faq: [
      { q: "Il Setter Inglese ha bisogno di un lavoro?", a: "Non obbligatorio ma molto utile. Nose work, tracking, riporto in acqua sono ottime alternative alla caccia per scaricarne l'energia." },
      { q: "Quanto movimento serve al Setter?", a: "Minimo 2 ore al giorno di corsa libera (non al guinzaglio stretto). E un cane che deve galoppare." },
    ],
  },
  {
    slug: "dobermann",
    nome: "Dobermann",
    taglia: "grande",
    energia: "alta",
    appartamento: "sconsigliato",
    bambini: "buono",
    pelo: "corto",
    esperienzaMinima: "esperto",
    costoMensile: 170,
    descrizione: "Nobile, atletico, protettivo. Richiede proprietario esperto e molto movimento.",
    caratteristiche: ["Guardiano eccellente", "Molto atletico", "Richiede esperienza"],
    foto: "https://images.unsplash.com/photo-1568572933382-74d440642117?w=800&q=80",
    origine: "Germania",
    pesoMinKg: 32, pesoMaxKg: 45, altezzaMinCm: 63, altezzaMaxCm: 72,
    vitaMediaMinAnni: 10, vitaMediaMaxAnni: 13,
    storia: "Selezionato nell'800 dall'esattore delle imposte Karl Friedrich Louis Dobermann in Germania. Voleva un cane da guardia che lo proteggesse nei giri di riscossione. Il risultato: un cane atletico, intelligente e temibile.",
    carattere: "Intelligente, atletico, territoriale. Molto legato alla famiglia ma diffidente con estranei. Non e aggressivo di default ma richiede socializzazione precocissima. Equilibrato con padroni coerenti.",
    addestramento: "Impara rapidamente ma necessita di padrone esperto. Sport cinofili IPO/Mondioring sono la sua vocazione naturale. Metodo positivo + fermezza.",
    salute: "Purtroppo razza con aspettativa di vita ridotta per patologie ereditarie.",
    saluteProblemi: ["Cardiomiopatia dilatativa (molto comune)", "Malattia di Von Willebrand", "Wobbler syndrome", "Displasia dell'anca"],
    alimentazione: "0.4-0.5 kg/giorno, 2-3 pasti per evitare torsione.",
    toelettatura: "Pelo corto: 1 spazzolatura a settimana.",
    idealePer: ["Padroni esperti", "Sport cinofili", "Guardia a persone", "Chi ha casa con giardino"],
    nonAdattoA: ["Prima esperienza", "Appartamento", "Famiglie sedentarie"],
    faq: [
      { q: "Il Dobermann orecchie tagliate: perche?", a: "La caudotomia e l'otectomia sono vietate in Italia dal 2007. Oggi i Dobermann italiani hanno orecchie naturali e coda lunga. E' piu sano ed etico." },
      { q: "Il Dobermann puo stare con bambini?", a: "Si, se socializzato da cucciolo. E protettivo ma mai aggressivo con i suoi bambini. Attenzione alla taglia: puo farli cadere giocando." },
    ],
  },
  {
    slug: "siberian-husky",
    nome: "Siberian Husky",
    taglia: "grande",
    energia: "alta",
    appartamento: "sconsigliato",
    bambini: "buono",
    pelo: "lungo",
    esperienzaMinima: "esperto",
    costoMensile: 160,
    descrizione: "Indipendente, atletico, stupendo. Non e per tutti: richiede tanto movimento.",
    caratteristiche: ["Cane da slitta", "Indipendente", "Soffre il caldo"],
    foto: "https://images.unsplash.com/photo-1605568427561-40dd23c2acea?w=800&q=80",
    origine: "Siberia",
    pesoMinKg: 15, pesoMaxKg: 27, altezzaMinCm: 50, altezzaMaxCm: 60,
    vitaMediaMinAnni: 12, vitaMediaMaxAnni: 14,
    storia: "Razza selezionata dalla popolazione Chukchi della Siberia orientale per tirare le slitte a grande distanza nel freddo estremo. Arrivato in Alaska nel 1908 e usato nelle corse di sleddog. E una delle razze piu antiche selezionate dall'uomo.",
    carattere: "Indipendente, quasi gatto-simile. Non e dipendente affettivamente dal padrone come un Labrador. Ulula piu che abbaiare. Tendenzialmente dolce con bambini ma non adatto come primo cane per carattere particolare.",
    addestramento: "Difficile. Intelligente ma con forte indipendenza, decide lui quando obbedire. Scappa dai giardini, scava, insegue. Richiede gestione esperta.",
    salute: "Razza robusta per origini estreme.",
    saluteProblemi: ["Displasia anca", "Problemi oculari (cataratta)", "Ipotiroidismo", "Problemi dermatologici"],
    alimentazione: "0.3-0.4 kg/giorno. Meno della media per la taglia (ottimo metabolismo).",
    toelettatura: "Doppio pelo folto: spazzola 2-3 volte a settimana, quotidiana durante muta (2 volte all'anno abbondantissime). Non tosare mai.",
    idealePer: ["Chi vive in zone fredde", "Sportivi che fanno canicross/skijoring", "Case con giardino recintato alto (1.8m minimo)"],
    nonAdattoA: ["Zone molto calde", "Appartamento", "Famiglie sedentarie", "Chi ha gatti o piccoli animali"],
    faq: [
      { q: "Posso avere un Husky in Italia?", a: "Si ma attento all'estate. Sopra i 30C soffre molto, servono casa climatizzata e uscite solo alba/tramonto." },
      { q: "Perche l'Husky scappa sempre?", a: "E' genetica: i Chukchi lasciavano i cani liberi in estate per cacciare. Il richiamo e molto debole. Giardino alto 1.8m con fondo in cemento (scavano)." },
    ],
  },
  {
    slug: "cane-corso",
    nome: "Cane Corso",
    taglia: "gigante",
    energia: "media",
    appartamento: "sconsigliato",
    bambini: "buono",
    pelo: "corto",
    esperienzaMinima: "esperto",
    costoMensile: 200,
    descrizione: "Molosso italiano imponente e protettivo. Richiede proprietario esperto.",
    caratteristiche: ["Molto protettivo", "Grande e forte", "Solo per esperti"],
    foto: "https://images.unsplash.com/photo-1593134257782-e89567b7718a?w=800&q=80",
    origine: "Italia (Meridione)",
    pesoMinKg: 40, pesoMaxKg: 55, altezzaMinCm: 60, altezzaMaxCm: 70,
    vitaMediaMinAnni: 9, vitaMediaMaxAnni: 12,
    storia: "Antico molosso italiano discendente dal Canis Pugnax romano, usato in guerra e nelle arene. Poi divenne cane da guardia nelle fattorie del Sud Italia. Riconosciuto ufficialmente come razza italiana nel 1994.",
    carattere: "Calmo, sicuro di se, equilibrato. Territoriale ma non nervoso. Estremamente fedele alla famiglia, non riconosce gli estranei senza socializzazione. Ottima guardia, richiede gestione esperta per la stazza.",
    addestramento: "Impara bene con metodo positivo e fermezza. Socializzazione obbligatoria dai 2 mesi. Non e un cane da sport agonistici ma ama il lavoro di protezione.",
    salute: "Aspettativa di vita ridotta per taglia gigante.",
    saluteProblemi: ["Displasia anca e gomito", "Torsione gastrica", "Epilessia", "Problemi cardiaci"],
    alimentazione: "0.5-0.7 kg/giorno, 2-3 pasti per evitare torsione.",
    toelettatura: "Pelo corto: 1 spazzolatura settimanale.",
    idealePer: ["Proprietari esperti", "Famiglie con bambini cresciuti", "Case con giardino grande recintato", "Chi cerca guardia seria"],
    nonAdattoA: ["Prima esperienza", "Appartamento", "Famiglie con bambini piccoli", "Anziani"],
    faq: [
      { q: "Il Cane Corso e legale in Italia?", a: "Si. Non e in nessuna lista di razze pericolose. E' una razza italiana riconosciuta FCI." },
      { q: "Quanto costa mantenere un Cane Corso?", a: "200-250 euro al mese solo di cibo di qualita per taglia gigante, piu veterinario e assicurazione. Budget annuale realistico: 3000-4000 euro." },
    ],
  },
  {
    slug: "meticcio",
    nome: "Meticcio da canile",
    taglia: "media",
    energia: "media",
    appartamento: "ottimo",
    bambini: "ottimo",
    pelo: "medio",
    esperienzaMinima: "principiante",
    costoMensile: 100,
    descrizione: "Ogni meticcio e unico. Adottare significa salvare una vita e avere un amico fedele.",
    caratteristiche: ["Adozione del cuore", "Grande varieta", "Spesso gia vaccinato"],
    foto: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&q=80",
    origine: "Ovunque",
    pesoMinKg: 5, pesoMaxKg: 40, altezzaMinCm: 25, altezzaMaxCm: 70,
    vitaMediaMinAnni: 10, vitaMediaMaxAnni: 16,
    storia: "Il meticcio non e una razza ma un cane con genealogie miste. Spesso e piu sano delle razze pure grazie alla variabilita genetica (effetto eterosi). Adottare un meticcio da canile o rifugio significa salvare una vita concreta.",
    carattere: "Infinitamente vario. Ogni meticcio ha un carattere unico. Generalmente i meticci sono piu equilibrati e meno nevrotici delle razze selezionate per estetica.",
    addestramento: "Dipende dalla combinazione genetica. Il personale del rifugio ti aiuta a capire il carattere del cane specifico.",
    salute: "Mediamente piu sani dei cani di razza per variabilita genetica.",
    saluteProblemi: ["Dipende dalle razze di provenienza", "In generale meno problemi ereditari"],
    alimentazione: "Dipende da taglia ed eta.",
    toelettatura: "Dipende dal pelo.",
    idealePer: ["Chi vuole salvare una vita", "Famiglie con bambini", "Prima esperienza cinofila (con supporto rifugio)"],
    nonAdattoA: ["Chi cerca a tutti i costi una razza specifica", "Chi vuole prevedere peso e aspetto adulto del cucciolo"],
    faq: [
      { q: "Dove posso adottare un meticcio?", a: "In ogni canile italiano ci sono centinaia di cani in attesa. Cerca su <a href='/adozioni'>la nostra sezione adozioni</a> o contatta il canile del tuo comune." },
      { q: "Adottare un meticcio adulto e difficile?", a: "No, spesso al contrario: i cani adulti hanno gia il carattere formato, sai cosa prendi. Molti rifugi li propongono con periodo di prova di 1-2 settimane." },
    ],
  },
  {
    slug: "carlino",
    nome: "Carlino (Pug)",
    taglia: "piccola",
    energia: "bassa",
    appartamento: "ottimo",
    bambini: "ottimo",
    pelo: "corto",
    esperienzaMinima: "principiante",
    costoMensile: 110,
    descrizione: "Piccolo, compatto, affettuoso. Il cane di compagnia per eccellenza, con problemi respiratori da conoscere.",
    caratteristiche: ["Adatto ad appartamento", "Affettuoso con tutti", "Brachicefalo, attenzione caldo"],
    foto: "https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?w=800&q=80",
    origine: "Cina",
    pesoMinKg: 6, pesoMaxKg: 8, altezzaMinCm: 25, altezzaMaxCm: 30,
    vitaMediaMinAnni: 12, vitaMediaMaxAnni: 15,
    storia: "Il Carlino e una razza antichissima cinese, presente alla corte imperiale gia 2.000 anni fa. Portato in Europa dai mercanti olandesi nel '500, divento il cane preferito delle nobildonne. La regina Vittoria d'Inghilterra ne fu grande appassionata. Oggi e tra le razze piccole piu' popolari al mondo.",
    carattere: "Allegro, sociale, perfetto in famiglia. Ama stare con le persone, va d'accordo con bambini, altri cani e gatti. Non e aggressivo. E' un compagno casalingo: ama il divano, mal sopporta le lunghe assenze. Russa fortissimo, fa rumori comici tipici dei brachicefali.",
    addestramento: "Buona predisposizione all'addestramento di base, anche se puo' essere un po' testardo. Metodo positivo con cibo (attenzione al peso). Non e' un cane sportivo: addestralo per buona educazione, non per agility.",
    salute: "Razza brachicefala: i problemi respiratori e termici sono il problema principale. Aspettativa di vita buona se ben gestito.",
    saluteProblemi: ["Sindrome BOAS respiratoria", "Intolleranza al caldo (mai sopra 25 gradi)", "Problemi oculari (occhi sporgenti)", "Allergie cutanee", "Obesita"],
    alimentazione: "0.10-0.15 kg/giorno di crocchette di qualita. Controllo peso rigoroso: anche 500g in piu' aggravano la respirazione.",
    toelettatura: "Pelo corto facile, ma muta abbondante. Spazzolatura 2-3 volte a settimana. Pulizia delle pieghe del muso ogni 2-3 giorni per evitare dermatiti.",
    idealePer: ["Anziani", "Appartamenti piccoli", "Chi non puo' fare sport con il cane", "Famiglie con bambini"],
    nonAdattoA: ["Sportivi attivi", "Chi vive in luoghi caldissimi senza aria condizionata", "Chi cerca cane da guardia"],
    faq: [
      { q: "Quanto costa un cucciolo di Carlino?", a: "Da allevamento serio LOI: 1.500-2.500 euro. Diffida da prezzi sotto i 1.000 euro: spesso cucciolate intensive senza controlli sanitari." },
      { q: "Il Carlino soffre davvero il caldo?", a: "Si', e' una delle razze piu' a rischio colpo di calore in Italia. Mai uscire sopra i 25 gradi nelle ore centrali. Aria condizionata in casa d'estate." },
      { q: "Carlino o Bulldog Francese?", a: "Caratteri simili (dolci, casalinghi), ma il Carlino tendenzialmente piu' resistente respiratoriamente del Bulldog Francese moderno. Entrambi brachicefali, entrambi richiedono cure dedicate." },
    ],
  },
  {
    slug: "yorkshire-terrier",
    nome: "Yorkshire Terrier",
    taglia: "piccola",
    energia: "media",
    appartamento: "ottimo",
    bambini: "medio",
    pelo: "lungo",
    esperienzaMinima: "principiante",
    costoMensile: 100,
    descrizione: "Piccolissimo (2-3 kg) ma con un grande temperamento da terrier. Affettuoso col padrone, diffidente con estranei.",
    caratteristiche: ["Mini, adatto ovunque", "Pelo lungo da curare", "Carattere deciso da terrier"],
    foto: "https://images.unsplash.com/photo-1583511666445-775f1f2116f5?w=800&q=80",
    origine: "Inghilterra (Yorkshire)",
    pesoMinKg: 2, pesoMaxKg: 3, altezzaMinCm: 18, altezzaMaxCm: 23,
    vitaMediaMinAnni: 12, vitaMediaMaxAnni: 16,
    storia: "Selezionato nell'800 nello Yorkshire dai minatori inglesi per la caccia ai topi nelle miniere. Inizialmente piu' grande, poi miniaturizzato per diventare cane di compagnia delle dame vittoriane. E' una delle razze di terrier piu' diffuse al mondo.",
    carattere: "Sotto l'aspetto da peluche c'e' un vero terrier: coraggioso, deciso, vivace, talvolta testardo. Forma un legame intensissimo con il padrone. Diffidente con estranei, abbaione, protettivo. Non e' adatto a bambini molto piccoli per la fragilita' fisica.",
    addestramento: "Intelligente e impara rapidamente, ma testardo. Socializzazione precoce essenziale per evitare aggressivita' verso estranei. Usa metodo positivo, niente punizioni (e' sensibile).",
    salute: "Razza generalmente robusta ma con fragilita' tipiche dei mini.",
    saluteProblemi: ["Lussazione della rotula", "Collasso tracheale (usa pettorina, mai collare)", "Problemi dentali", "Ipoglicemia nei cuccioli", "Atrofia retinica progressiva"],
    alimentazione: "0.05-0.08 kg/giorno di crocchette mini-breed di qualita. Pasti frequenti per evitare ipoglicemia. Mai cibi umani.",
    toelettatura: "Pelo lungo richiede impegno: spazzolatura quotidiana, bagno mensile, tosatura ogni 2-3 mesi se non si tiene pelo lungo da esposizione. Molti proprietari preferiscono taglio corto pratico.",
    idealePer: ["Anziani", "Appartamenti piccoli", "Single", "Chi cerca un cane di compagnia"],
    nonAdattoA: ["Famiglie con bambini molto piccoli", "Chi non puo' dedicare tempo alla toelettatura"],
    faq: [
      { q: "Quanto costa un cucciolo di Yorkshire?", a: "Da allevamento serio LOI: 800-1.800 euro. Diffida dei 'Teacup' venduti come iper-mini: sono cuccioli nati malati o sottosviluppati per gli standard FCI." },
      { q: "Yorkshire e bambini: vanno d'accordo?", a: "Con bambini sopra i 7-8 anni educati al rispetto del cane si'. Con bambini piccoli e' rischioso: il cane e' fragile e puo' reagire con morsi se gestito male." },
      { q: "Yorkshire soffre il freddo?", a: "Si', moltissimo. Cappotto in inverno obbligatorio, mai uscite lunghe sotto i 5 gradi." },
    ],
  },
  {
    slug: "cocker-spaniel-inglese",
    nome: "Cocker Spaniel Inglese",
    taglia: "media",
    energia: "alta",
    appartamento: "medio",
    bambini: "ottimo",
    pelo: "lungo",
    esperienzaMinima: "principiante",
    costoMensile: 130,
    descrizione: "Dolce, allegro, eternamente cucciolo. Sportivo da caccia trasformato in cane da famiglia.",
    caratteristiche: ["Affettuoso e socievole", "Pelo da curare regolarmente", "Energia alta"],
    foto: "https://images.unsplash.com/photo-1622682135829-a4cda2706cd2?w=800&q=80",
    origine: "Inghilterra",
    pesoMinKg: 12, pesoMaxKg: 16, altezzaMinCm: 38, altezzaMaxCm: 43,
    vitaMediaMinAnni: 12, vitaMediaMaxAnni: 15,
    storia: "Il Cocker nasce in Inghilterra nell'800 come cane da caccia specializzato nelle beccacce. Selezionato per dimensione media, naso fine, pelo resistente ai rovi. Nel '900 e' diventato uno dei cani da famiglia piu' amati al mondo grazie al carattere dolce e all'aspetto da eterno cucciolo.",
    carattere: "Allegro, sociale, sempre di buon umore. Ama la famiglia, e' paziente con i bambini, va d'accordo con altri cani. E' attivo: ama correre, nuotare, riportare. Non sopporta la solitudine: lasciato spesso solo sviluppa ansia. Tendenza ad abbaiare.",
    addestramento: "Intelligente e desideroso di compiacere, facile per principianti. Metodo positivo, niente punizioni (e' sensibile). Ama riportare oggetti: incanala questa passione in esercizi e giochi quotidiani.",
    salute: "Robusto ma con predisposizioni ereditarie da monitorare.",
    saluteProblemi: ["Otite cronica (orecchie pendule)", "Problemi oculari (cataratta, glaucoma, PRA)", "Displasia anca", "Sindrome di rabbia idiopatica (rara, particolari linee)", "Patologie autoimmuni"],
    alimentazione: "0.20-0.30 kg/giorno di crocchette di qualita per taglia media. Tendenza a ingrassare: dosi misurate.",
    toelettatura: "Pelo lungo richiede spazzolatura 3-4 volte a settimana, toelettatura professionale ogni 2-3 mesi. Pulizia orecchie 1-2 volte a settimana (otiti frequenti). Bagno ogni 4-6 settimane.",
    idealePer: ["Famiglie con bambini", "Sportivi e amanti delle passeggiate lunghe", "Chi ama nuoto e attivita' acquatiche"],
    nonAdattoA: ["Chi sta fuori casa 10+ ore", "Chi non puo' dedicare tempo a toelettatura"],
    faq: [
      { q: "Quanto costa un cucciolo di Cocker?", a: "Da allevamento serio LOI: 800-1.500 euro. Importante scegliere allevatori con test sanitari sui genitori (PRA, displasia, sindrome di rabbia idiopatica)." },
      { q: "Cocker Inglese o Americano?", a: "L'Inglese e' piu' grande, pelo piu' lungo, originale. L'Americano (piu' piccolo, muso piu' corto, pelo a volte gonfio) e' molto popolare in USA ma piu' raro in Italia." },
      { q: "Cocker abbaia molto?", a: "Si', tende ad abbaiare al campanello, ai rumori, agli estranei. Socializzazione precoce e addestramento aiutano a ridurre, mai eliminare del tutto." },
    ],
  },
  {
    slug: "volpino-italiano",
    nome: "Volpino Italiano",
    taglia: "piccola",
    energia: "media",
    appartamento: "ottimo",
    bambini: "buono",
    pelo: "lungo",
    esperienzaMinima: "principiante",
    costoMensile: 95,
    descrizione: "Razza italiana antichissima, simile allo Spitz. Piccolo, vivace, leale, raro anche in Italia.",
    caratteristiche: ["Razza italiana storica", "Eccellente cane d'allarme", "Pelo bianco caratteristico"],
    foto: "https://images.unsplash.com/photo-1583337426008-2fef51aa841a?w=800&q=80",
    origine: "Italia",
    pesoMinKg: 4, pesoMaxKg: 5, altezzaMinCm: 25, altezzaMaxCm: 30,
    vitaMediaMinAnni: 14, vitaMediaMaxAnni: 16,
    storia: "Il Volpino Italiano e una razza antichissima documentata gia' nel Medioevo, allevata nelle corti italiane come cane di compagnia e d'allarme. Michelangelo ne possedette uno. Quasi estinta nel dopoguerra (50 esemplari negli anni '60), oggi e' stata salvata grazie agli sforzi di pochi allevatori italiani.",
    carattere: "Vivace, attento, intelligente. Forma legami profondi con la famiglia, diffidente con gli estranei. E' un eccellente cane d'allarme: abbaia ad ogni rumore sospetto. Coraggioso nonostante la piccola taglia. Non e' aggressivo se ben socializzato.",
    addestramento: "Intelligente e collaborativo. Imparare le basi e' facile, ma serve coerenza per gestire la tendenza all'abbaio eccessivo. Socializzazione precoce con estranei per evitare diffidenza.",
    salute: "Razza generalmente sana e longeva.",
    saluteProblemi: ["Lussazione rotula", "Problemi dentali", "Atrofia progressiva retina (rara)"],
    alimentazione: "0.08-0.12 kg/giorno di crocchette mini-breed di qualita. Cane parco mangiatore.",
    toelettatura: "Pelo lungo bianco richiede spazzolatura 3-4 volte a settimana. Bagno mensile. Pelo non perde molto in muta.",
    idealePer: ["Famiglie con bambini sopra i 6 anni", "Anziani attivi", "Chi cerca razza italiana storica"],
    nonAdattoA: ["Chi cerca cane silenzioso", "Famiglie con bambini molto piccoli"],
    faq: [
      { q: "Quanto e raro il Volpino Italiano oggi?", a: "Molto raro: poche centinaia di esemplari iscritti annualmente all'ENCI. Per trovare un cucciolo da allevamento serio servono spesso 6-12 mesi di attesa." },
      { q: "Quanto costa un cucciolo di Volpino?", a: "Da allevamento ENCI: 1.000-1.800 euro. Pochi allevamenti seri in Italia, ricerca attiva e attesa necessarie." },
      { q: "Differenza tra Volpino Italiano e Spitz Tedesco?", a: "Razze diverse: il Volpino e' piu' antico, italiano, solo bianco (raramente rosso); lo Spitz Tedesco e' tedesco, colori vari, taglie diverse (dal Pomerania al Wolfspitz)." },
    ],
  },
  {
    slug: "lagotto-romagnolo",
    nome: "Lagotto Romagnolo",
    taglia: "media",
    energia: "alta",
    appartamento: "medio",
    bambini: "ottimo",
    pelo: "lungo",
    esperienzaMinima: "principiante",
    costoMensile: 140,
    descrizione: "Razza italiana, il cane da tartufo per eccellenza. Affettuoso, intelligente, pelo riccio caratteristico.",
    caratteristiche: ["Razza italiana", "Cane da tartufo storico", "Ipoallergenico (pelo che non muta)"],
    foto: "https://images.unsplash.com/photo-1605568427561-40dd23c2acea?w=800&q=80",
    origine: "Italia (Romagna)",
    pesoMinKg: 11, pesoMaxKg: 16, altezzaMinCm: 41, altezzaMaxCm: 48,
    vitaMediaMinAnni: 14, vitaMediaMaxAnni: 17,
    storia: "Il Lagotto Romagnolo e' una razza italiana antichissima della Romagna, originariamente cane da riporto in acqua nelle valli di Comacchio. Dopo la bonifica delle paludi, e' stato riconvertito per la cerca del tartufo. E' l'unica razza al mondo specializzata in questo lavoro. Riconosciuto dall'FCI nel 1995.",
    carattere: "Affettuoso, equilibrato, intelligente. Forma un legame profondo con la famiglia, e' gentile con bambini e altri animali. Ha un olfatto eccezionale e una passione per la ricerca: necessita di attivita' mentale costante. Non e' aggressivo, non e' un cane da guardia.",
    addestramento: "Estremamente intelligente, facile da addestrare. Eccelle nella ricerca olfattiva (tartufo, nosework, mantrailing). Ha bisogno di stimoli mentali quotidiani per non annoiarsi.",
    salute: "Razza robusta e longeva.",
    saluteProblemi: ["Displasia anca", "Mioclono benigno giovanile (test genetico disponibile)", "Lisosomiale a deposito (test genetico)", "Otiti per pelo nelle orecchie"],
    alimentazione: "0.20-0.30 kg/giorno di crocchette di qualita per taglia media. Apprezza ricerca olfattiva del cibo (kong, tappetini olfattivi).",
    toelettatura: "Pelo riccio non muta (ipoallergenico, ma non al 100%). Toelettatura professionale ogni 2-3 mesi. Spazzolatura 1-2 volte a settimana. Mai tagliare a zero (rovina la struttura del pelo).",
    idealePer: ["Famiglie con bambini", "Chi soffre di allergie", "Amanti della ricerca olfattiva", "Sportivi"],
    nonAdattoA: ["Chi sta fuori casa 10+ ore", "Chi non vuole stimolare mentalmente il cane"],
    faq: [
      { q: "Quanto costa un cucciolo di Lagotto?", a: "Da allevamento ENCI: 1.500-2.500 euro. Linee da lavoro (selezione per ricerca tartufo) costano simile alle linee da bellezza. Diffida prezzi sotto i 1.200 euro." },
      { q: "Il Lagotto e' davvero ipoallergenico?", a: "Quasi: il pelo non muta come cane normale, riducendo allergeni nell'ambiente. Ma non e' ipoallergenico al 100% (allergie possono comunque scatenarsi)." },
      { q: "Posso usare il Lagotto per cercare tartufi?", a: "Si', e' la sua specializzazione! Esistono corsi di addestramento alla cerca tartufi, sia per uso personale che per esposizione (gare di ricerca)." },
    ],
  },
  {
    slug: "maremmano-abruzzese",
    nome: "Pastore Maremmano-Abruzzese",
    taglia: "grande",
    energia: "media",
    appartamento: "sconsigliato",
    bambini: "buono",
    pelo: "lungo",
    esperienzaMinima: "intermedio",
    costoMensile: 170,
    descrizione: "Razza italiana antichissima, il cane da guardia delle greggi. Imponente, leale, protettivo della famiglia.",
    caratteristiche: ["Razza italiana storica", "Eccellente cane da guardia", "Indipendente"],
    foto: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=800&q=80",
    origine: "Italia (Abruzzo e Maremma)",
    pesoMinKg: 30, pesoMaxKg: 45, altezzaMinCm: 60, altezzaMaxCm: 73,
    vitaMediaMinAnni: 11, vitaMediaMaxAnni: 13,
    storia: "Il Maremmano-Abruzzese discende da cani guardia del bestiame presenti in Italia da almeno 2.000 anni. Selezionato per proteggere greggi di pecore da lupi e orsi in Abruzzo e Maremma, e' uno dei piu' antichi cani da pastore d'Italia. Ancora oggi usato nelle transumanze e nei progetti di conservazione del lupo (proteggere bestiame senza uccidere predatori).",
    carattere: "Indipendente, equilibrato, profondamente protettivo. Non e' un cane affettuoso da carezze continue: e' un guardiano. Ama la sua famiglia e la difende con vita. Diffidente con estranei, calmo se ben gestito. Non e' aggressivo senza motivo. Non e' adatto come primo cane.",
    addestramento: "Cane da pastore indipendente, non e' un retriever che esegue ordini. Educazione coerente fin da cucciolo, socializzazione massiva nei primi 4 mesi. Mai durezza: il Maremmano rispetta chi e' fermo ma rispettoso. Esperienza cinofila necessaria.",
    salute: "Razza generalmente robusta, costruita per lavoro.",
    saluteProblemi: ["Displasia anca/gomito", "Torsione gastrica", "Patologie cardiache senili", "Sensibilita' a calore"],
    alimentazione: "0.50-0.80 kg/giorno di crocchette di qualita per taglia grande. Mai esercizio dopo pasto (torsione gastrica).",
    toelettatura: "Pelo lungo bianco doppio: spazzolatura 2-3 volte a settimana, intensiva in muta (primavera/autunno). Pelo si pulisce abbastanza da solo. Mai tagliare a zero.",
    idealePer: ["Case con giardino grande", "Chi cerca cane da guardia equilibrato", "Allevatori, agricoltori"],
    nonAdattoA: ["Appartamenti", "Prima esperienza cinofila", "Chi vuole cane sempre obbediente come Labrador"],
    faq: [
      { q: "Quanto costa un cucciolo di Maremmano?", a: "Da allevamento ENCI: 800-1.500 euro. Linee da lavoro (selezionate per guardiania attiva del gregge) hanno prezzi simili ma carattere piu' forte." },
      { q: "Il Maremmano e' adatto in famiglia?", a: "Si', se la famiglia accetta di gestire un cane indipendente, grande, abbaione di notte. E' protettivo con bambini di casa ma diffidente con estranei. Richiede spazio." },
      { q: "Maremmano e altri cani?", a: "Da cucciolo socializzato bene va d'accordo con altri cani. Da adulto puo' essere territoriale, specie con cani dello stesso sesso." },
    ],
  },
  {
    slug: "spinone-italiano",
    nome: "Spinone Italiano",
    taglia: "grande",
    energia: "alta",
    appartamento: "sconsigliato",
    bambini: "ottimo",
    pelo: "medio",
    esperienzaMinima: "intermedio",
    costoMensile: 160,
    descrizione: "Razza italiana antichissima, cane da caccia versatile. Equilibrato, dolce con la famiglia, instancabile in campo.",
    caratteristiche: ["Razza italiana storica", "Cane da caccia versatile", "Dolce con bambini"],
    foto: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800&q=80",
    origine: "Italia (Piemonte)",
    pesoMinKg: 28, pesoMaxKg: 39, altezzaMinCm: 58, altezzaMaxCm: 70,
    vitaMediaMinAnni: 10, vitaMediaMaxAnni: 12,
    storia: "Lo Spinone Italiano e' una delle razze italiane piu' antiche, documentata gia' nel Rinascimento. Selezionato in Piemonte come cane da ferma, punta e riporto, capace di lavorare in ogni terreno: pianura, bosco, palude. Il pelo duro lo protegge dai rovi. E' un cane da lavoro vero, ma anche un eccellente compagno.",
    carattere: "Equilibrato, dolce, paziente. Ottimo con bambini, sociale con altri cani. Ha grande resistenza fisica ma in casa e' calmo, perfino pigro. Forma un legame profondo con la famiglia. Non e' aggressivo. Buon cane d'allarme ma non da guardia attiva.",
    addestramento: "Intelligente e collaborativo, ma con la testardaggine tipica dei cani da caccia. Metodo positivo, esercizi vari per evitare noia. Eccelle in retrieve, mantrailing, attivita' olfattive. Necessita di esercizio quotidiano significativo.",
    salute: "Robusto, ma con problemi tipici delle taglie grandi.",
    saluteProblemi: ["Displasia anca/gomito", "Torsione gastrica", "Atassia cerebellare (test genetico)", "Otiti per orecchie pendule"],
    alimentazione: "0.40-0.60 kg/giorno di crocchette di qualita. Mai esercizio dopo pasto (torsione gastrica).",
    toelettatura: "Pelo duro medio: spazzolatura settimanale + 'stripping' (toelettatura specifica) ogni 3-4 mesi. La barba caratteristica va pulita dopo ogni pasto.",
    idealePer: ["Famiglie sportive con bambini", "Case con giardino", "Cacciatori"],
    nonAdattoA: ["Appartamenti piccoli", "Chi non puo' garantire 2 ore movimento al giorno"],
    faq: [
      { q: "Quanto costa un cucciolo di Spinone?", a: "Da allevamento ENCI: 1.000-1.800 euro. Allevamenti seri in Piemonte e nord Italia. Test sanitari sui genitori obbligatori." },
      { q: "Lo Spinone e' adatto in citta'?", a: "Si', solo se garantisci 2 ore di movimento al giorno. In appartamento puo' funzionare con disciplina sportiva, ma e' un cane fatto per la campagna." },
      { q: "Spinone o Bracco Italiano?", a: "Lo Spinone ha pelo duro, e' piu' adattabile a condizioni difficili. Il Bracco e' a pelo corto, piu' elegante, simile temperamento. Entrambi cani da caccia italiani versatili." },
    ],
  },
  {
    slug: "bovaro-bernese",
    nome: "Bovaro del Bernese",
    taglia: "grande",
    energia: "media",
    appartamento: "sconsigliato",
    bambini: "ottimo",
    pelo: "lungo",
    esperienzaMinima: "principiante",
    costoMensile: 200,
    descrizione: "Gigante gentile dalla Svizzera. Calmo, affettuoso, instancabile con bambini. Aspettativa di vita purtroppo breve.",
    caratteristiche: ["Gentile con bambini", "Cane da famiglia per eccellenza", "Vita media breve"],
    foto: "https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=800&q=80",
    origine: "Svizzera (Berna)",
    pesoMinKg: 36, pesoMaxKg: 50, altezzaMinCm: 58, altezzaMaxCm: 70,
    vitaMediaMinAnni: 7, vitaMediaMaxAnni: 10,
    storia: "Il Bovaro del Bernese nasce nelle Alpi svizzere come cane da fattoria: trainava carri, sorvegliava bestiame, accompagnava i contadini. Quasi estinto a fine '800, e' stato salvato dal cinofilo Albert Heim. Oggi e' una delle razze giganti piu' popolari al mondo per il carattere dolce e l'aspetto fotogenico.",
    carattere: "Calmo, equilibrato, eccezionalmente paziente con bambini. Forma legami profondi con la famiglia. Non e' un cane da guardia attiva (troppo gentile), ma di presenza imponente. Mai aggressivo. Ama stare con le persone, soffre la solitudine.",
    addestramento: "Intelligente e desideroso di compiacere. Facile da addestrare ma maturazione mentale lenta (matura a 2-3 anni). Niente esercizio intenso nei primi 12-14 mesi (articolazioni in crescita). Metodo positivo, mai durezza.",
    salute: "Purtroppo razza con vita media breve, predisposta a tumori e patologie ortopediche.",
    saluteProblemi: ["Istiocitoma maligno (tumore aggressivo, principale causa morte)", "Displasia anca/gomito", "Torsione gastrica", "Patologie cardiache"],
    alimentazione: "0.60-0.80 kg/giorno di crocchette di qualita per giant breed. Mai esercizio dopo pasto. Mantenere peso corretto per articolazioni.",
    toelettatura: "Pelo lungo a tre colori: spazzolatura 3-4 volte a settimana, intensiva in muta. Bagno ogni 2 mesi. Mai tosatura a zero. Soffre il caldo: protezione estiva essenziale.",
    idealePer: ["Famiglie con bambini", "Case con giardino", "Chi cerca gigante gentile"],
    nonAdattoA: ["Appartamenti", "Climi caldissimi", "Chi non puo' affrontare emotivamente la vita breve"],
    faq: [
      { q: "Quanto costa un cucciolo di Bovaro del Bernese?", a: "Da allevamento ENCI con test sanitari completi: 1.800-3.000 euro. Diffida prezzi inferiori: razza con problemi ereditari gravi, solo selezione seria riduce rischi." },
      { q: "Davvero vive solo 7-10 anni?", a: "Si', purtroppo. La razza ha alta incidenza di istiocitoma maligno (tumore aggressivo) e altre patologie. Linee selezionate per longevita' esistono ma sono minoranza." },
      { q: "Bovaro Bernese in appartamento?", a: "Difficile. La taglia, il pelo lungo, la sensibilita' al caldo lo rendono adatto a case con giardino e clima temperato. Non e' un cane da appartamento."},
    ],
  },
  {
    slug: "pomerania",
    nome: "Pomerania (Spitz Tedesco Nano)",
    taglia: "piccola",
    energia: "media",
    appartamento: "ottimo",
    bambini: "medio",
    pelo: "lungo",
    esperienzaMinima: "principiante",
    costoMensile: 100,
    descrizione: "Piccolissimo (2-3 kg) ma con personalita' enorme. Vivace, intelligente, perfetto da appartamento, in crescita di popolarita'.",
    caratteristiche: ["Mini taglia", "Pelo gonfio caratteristico", "Vivace e abbaione"],
    foto: "https://images.unsplash.com/photo-1583512603805-3cc6b41f3edb?w=800&q=80",
    origine: "Germania (Pomerania)",
    pesoMinKg: 2, pesoMaxKg: 3, altezzaMinCm: 18, altezzaMaxCm: 22,
    vitaMediaMinAnni: 12, vitaMediaMaxAnni: 16,
    storia: "Il Pomerania discende dagli Spitz tedeschi, miniaturizzato nell'800 in Germania settentrionale (Pomerania). Reso popolare dalla regina Vittoria d'Inghilterra che ne possedeva esemplari piccolissimi. Oggi e' tra le razze piccole piu' di moda al mondo, complici i social media.",
    carattere: "Vivace, intelligente, sociale, leale al padrone. Forma legami intensi con la famiglia. Diffidente con estranei, abbaione (cane d'allarme). Coraggioso nonostante la taglia. Non e' un cane sportivo ma ama uscite quotidiane.",
    addestramento: "Molto intelligente e collaborativo. Imparare le basi e' facile. Socializzazione precoce per gestire l'abbaio eccessivo. Trick training (esercizi divertenti) lo entusiasma.",
    salute: "Razza generalmente longeva ma con fragilita' tipiche dei mini.",
    saluteProblemi: ["Lussazione rotula", "Collasso tracheale", "Problemi dentali", "Alopecia X (calo pelo)", "Cardiomiopatia"],
    alimentazione: "0.05-0.08 kg/giorno di crocchette mini-breed di qualita. Pasti frequenti per evitare ipoglicemia cuccioli.",
    toelettatura: "Pelo doppio caratteristico: spazzolatura 3-4 volte a settimana per evitare nodi. Bagno ogni 4-6 settimane. Mai tosare al rasoio (rovina struttura pelo). Toelettatura professionale per look 'orsetto'.",
    idealePer: ["Anziani", "Single", "Appartamenti", "Chi cerca cane piccolo vivace"],
    nonAdattoA: ["Famiglie con bambini piccoli (fragilita' fisica)", "Chi cerca cane silenzioso"],
    faq: [
      { q: "Quanto costa un cucciolo di Pomerania?", a: "Da allevamento ENCI: 1.500-3.000 euro. Diffida dei 'Boo' commerciali venduti come iper-mini: spesso cuccioli malati o tagliati con fini estetici." },
      { q: "Pomerania e' adatto in famiglia con bambini?", a: "Con bambini sopra i 7-8 anni educati al rispetto. Con bambini piccoli rischioso per la fragilita' del cane." },
      { q: "Differenza tra Pomerania e Spitz Tedesco?", a: "Il Pomerania e' la varieta' nana dello Spitz Tedesco (esistono altre taglie: piccolo, medio, grande, Wolfspitz). Stesso standard, dimensioni diverse." },
    ],
  },
  {
    slug: "pastore-australiano",
    nome: "Pastore Australiano (Australian Shepherd)",
    taglia: "media",
    energia: "alta",
    appartamento: "sconsigliato",
    bambini: "ottimo",
    pelo: "lungo",
    esperienzaMinima: "intermedio",
    costoMensile: 160,
    descrizione: "Intelligente, atletico, dai bellissimi occhi (spesso azzurri o eterocromia). Cane sportivo per famiglie attive.",
    caratteristiche: ["Intelligenza altissima", "Pelo multicolore caratteristico", "Energia enorme"],
    foto: "https://images.unsplash.com/photo-1568572933382-74d440642117?w=800&q=80",
    origine: "Stati Uniti (nonostante il nome)",
    pesoMinKg: 16, pesoMaxKg: 30, altezzaMinCm: 46, altezzaMaxCm: 58,
    vitaMediaMinAnni: 12, vitaMediaMaxAnni: 15,
    storia: "Nonostante il nome, il Pastore Australiano e' stato sviluppato negli Stati Uniti dell'Ovest nell'800-900 come cane da pastore per i ranch. Probabilmente da pastori baschi emigrati via Australia (da qui il nome) negli USA. Oggi e' una delle razze pastore piu' popolari al mondo, eccellente in sport cinofili.",
    carattere: "Intelligentissimo, sensibile, attivo. Forma legami profondi con la famiglia, e' eccellente con bambini. Lavoratore instancabile: senza attivita' fisica e mentale sviluppa comportamenti compulsivi (come il Border Collie). Sociale con altri cani se ben socializzato.",
    addestramento: "Estremamente intelligente, facilissimo da addestrare ma serve esperienza per gestire energia e intelligenza. Eccelle in agility, frisbee, obedience, herding. Necessita di attivita' mentale costante.",
    salute: "Razza generalmente robusta.",
    saluteProblemi: ["Sensibilita' MDR1 (test genetico, alcuni farmaci tossici)", "CEA (Collie Eye Anomaly)", "Displasia anca", "Epilessia (rara)", "Sordita' nei merle doppi"],
    alimentazione: "0.25-0.35 kg/giorno di crocchette di qualita. Sportivo, brucia calorie facilmente.",
    toelettatura: "Pelo medio doppio: spazzolatura 2-3 volte a settimana, intensiva in muta. Mai tosare a zero. Pulizia orecchie regolare.",
    idealePer: ["Sportivi", "Famiglie attive con bambini", "Praticanti agility/frisbee", "Case con giardino"],
    nonAdattoA: ["Sedentari", "Appartamenti piccoli", "Chi non puo' garantire 3+ ore attivita' al giorno"],
    faq: [
      { q: "Quanto costa un cucciolo di Pastore Australiano?", a: "Da allevamento serio LOI con test genetici: 1.200-2.500 euro. Linee da lavoro (selezionate per herding/agility) e linee da bellezza hanno prezzi simili." },
      { q: "Pastore Australiano in appartamento?", a: "Molto difficile. Razza ad altissima energia, senza 3 ore di attivita' al giorno sviluppa nevrosi. Se hai dubbi, scegli un'altra razza." },
      { q: "Differenza tra Pastore Australiano e Border Collie?", a: "Border Collie e' piu' intenso, focalizzato sul lavoro, pelo piu' liscio. Pastore Australiano e' piu' adattabile alla vita di famiglia, pelo piu' folto, occhi spesso azzurri/eterocromia. Entrambi richiedono molta attivita'." },
    ],
  },
];
