export type Taglia = "piccola" | "media" | "grande" | "gigante";
export type Energia = "bassa" | "media" | "alta";
export type Appartamento = "ottimo" | "medio" | "sconsigliato";
export type Bambini = "ottimo" | "buono" | "medio";
export type Pelo = "corto" | "medio" | "lungo";
export type Esperienza = "principiante" | "intermedio" | "esperto";

export interface Razza {
  slug: string;
  nome: string;
  taglia: Taglia;
  energia: Energia;
  appartamento: Appartamento;
  bambini: Bambini;
  pelo: Pelo;
  esperienzaMinima: Esperienza;
  costoMensile: number;
  descrizione: string;
  caratteristiche: string[];
  foto: string;
  magazineSlug?: string;
}

export const RAZZE: Razza[] = [
  {
    slug: "labrador-retriever",
    nome: "Labrador Retriever",
    taglia: "grande",
    energia: "alta",
    appartamento: "medio",
    bambini: "ottimo",
    pelo: "corto",
    esperienzaMinima: "principiante",
    costoMensile: 150,
    descrizione: "Il cane da famiglia per eccellenza: affettuoso, socievole, instancabile.",
    caratteristiche: ["Ottimo con bambini", "Facile da addestrare", "Molto attivo"],
    foto: "https://images.unsplash.com/photo-1591160690555-5debfba289f0?w=600&q=80",
  },
  {
    slug: "golden-retriever",
    nome: "Golden Retriever",
    taglia: "grande",
    energia: "alta",
    appartamento: "medio",
    bambini: "ottimo",
    pelo: "lungo",
    esperienzaMinima: "principiante",
    costoMensile: 170,
    descrizione: "Dolce, paziente e intelligente. Adora la famiglia e le lunghe passeggiate.",
    caratteristiche: ["Tenero e paziente", "Adatto a famiglie", "Necessita toelettatura"],
    foto: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=600&q=80",
  },
  {
    slug: "pastore-tedesco",
    nome: "Pastore Tedesco",
    taglia: "grande",
    energia: "alta",
    appartamento: "sconsigliato",
    bambini: "buono",
    pelo: "medio",
    esperienzaMinima: "intermedio",
    costoMensile: 160,
    descrizione: "Intelligente, leale, protettivo. Richiede spazio e un proprietario presente.",
    caratteristiche: ["Molto intelligente", "Guardiano naturale", "Necessita spazio"],
    foto: "https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=600&q=80",
  },
  {
    slug: "border-collie",
    nome: "Border Collie",
    taglia: "media",
    energia: "alta",
    appartamento: "sconsigliato",
    bambini: "buono",
    pelo: "medio",
    esperienzaMinima: "esperto",
    costoMensile: 140,
    descrizione: "Il cane piu intelligente del mondo. Ha bisogno di tanto movimento e stimoli mentali.",
    caratteristiche: ["Super intelligente", "Ideale per sport cinofili", "Non adatto a sedentari"],
    foto: "https://images.unsplash.com/photo-1503256207526-0d5d80fa2f47?w=600&q=80",
  },
  {
    slug: "jack-russell-terrier",
    nome: "Jack Russell Terrier",
    taglia: "piccola",
    energia: "alta",
    appartamento: "ottimo",
    bambini: "buono",
    pelo: "corto",
    esperienzaMinima: "intermedio",
    costoMensile: 90,
    descrizione: "Piccolo ma con l'energia di un grande cane. Vivace, curioso, coraggioso.",
    caratteristiche: ["Esplosivo di energia", "Ottimo per attivita", "Testardo"],
    foto: "https://images.unsplash.com/photo-1597633244018-0201d0158aab?w=600&q=80",
  },
  {
    slug: "chihuahua",
    nome: "Chihuahua",
    taglia: "piccola",
    energia: "media",
    appartamento: "ottimo",
    bambini: "medio",
    pelo: "corto",
    esperienzaMinima: "principiante",
    costoMensile: 70,
    descrizione: "Il piu piccolo del mondo. Fedele al padrone, ideale per la vita in citta.",
    caratteristiche: ["Perfetto in appartamento", "Poco impegnativo", "Molto legato al padrone"],
    foto: "https://images.unsplash.com/photo-1605568427561-40dd23c2acea?w=600&q=80",
  },
  {
    slug: "bulldog-francese",
    nome: "Bulldog Francese",
    taglia: "piccola",
    energia: "bassa",
    appartamento: "ottimo",
    bambini: "ottimo",
    pelo: "corto",
    esperienzaMinima: "principiante",
    costoMensile: 110,
    descrizione: "Divertente, affettuoso e adatto alla vita in appartamento. Poche passeggiate.",
    caratteristiche: ["Pigro e coccolone", "Perfetto in citta", "Attenzione al caldo"],
    foto: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=600&q=80",
  },
  {
    slug: "beagle",
    nome: "Beagle",
    taglia: "media",
    energia: "alta",
    appartamento: "medio",
    bambini: "ottimo",
    pelo: "corto",
    esperienzaMinima: "intermedio",
    costoMensile: 120,
    descrizione: "Socievole, curioso, vorace. Perfetto in famiglia ma segue sempre il naso.",
    caratteristiche: ["Allegro e socievole", "Adora i bambini", "Tende a fuggire"],
    foto: "https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=600&q=80",
  },
  {
    slug: "cavalier-king-charles",
    nome: "Cavalier King Charles",
    taglia: "piccola",
    energia: "media",
    appartamento: "ottimo",
    bambini: "ottimo",
    pelo: "lungo",
    esperienzaMinima: "principiante",
    costoMensile: 120,
    descrizione: "Dolcissimo cane da compagnia, affettuoso con tutti, ideale per la famiglia.",
    caratteristiche: ["Super coccolone", "Ottimo con bambini", "Richiede compagnia"],
    foto: "https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=600&q=80",
  },
  {
    slug: "bassotto",
    nome: "Bassotto",
    taglia: "piccola",
    energia: "media",
    appartamento: "ottimo",
    bambini: "buono",
    pelo: "corto",
    esperienzaMinima: "intermedio",
    costoMensile: 90,
    descrizione: "Coraggioso, testardo, affettuoso. Perfetto in appartamento, ama scavare.",
    caratteristiche: ["Carattere forte", "Ideale in citta", "Attenzione alla schiena"],
    foto: "https://images.unsplash.com/photo-1612536057832-2ff7ead58194?w=600&q=80",
  },
  {
    slug: "boxer",
    nome: "Boxer",
    taglia: "grande",
    energia: "alta",
    appartamento: "medio",
    bambini: "ottimo",
    pelo: "corto",
    esperienzaMinima: "intermedio",
    costoMensile: 150,
    descrizione: "Giocherellone eterno, fedele e protettivo. Ottimo cane da famiglia attiva.",
    caratteristiche: ["Eternamente cucciolo", "Protettivo", "Molto giocoso"],
    foto: "https://images.unsplash.com/photo-1568572933382-74d440642117?w=600&q=80",
  },
  {
    slug: "rottweiler",
    nome: "Rottweiler",
    taglia: "grande",
    energia: "media",
    appartamento: "sconsigliato",
    bambini: "buono",
    pelo: "corto",
    esperienzaMinima: "esperto",
    costoMensile: 180,
    descrizione: "Forte, leale, protettivo. Richiede un proprietario esperto e addestramento.",
    caratteristiche: ["Molto protettivo", "Richiede esperienza", "Fedele alla famiglia"],
    foto: "https://images.unsplash.com/photo-1567752881298-894bb81f9379?w=600&q=80",
  },
  {
    slug: "shih-tzu",
    nome: "Shih Tzu",
    taglia: "piccola",
    energia: "bassa",
    appartamento: "ottimo",
    bambini: "ottimo",
    pelo: "lungo",
    esperienzaMinima: "principiante",
    costoMensile: 130,
    descrizione: "Piccolo, elegante, affettuoso. Ideale per chi cerca un compagno tranquillo.",
    caratteristiche: ["Tranquillo e dolce", "Perfetto in appartamento", "Molta toelettatura"],
    foto: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=600&q=80",
  },
  {
    slug: "maltese",
    nome: "Maltese",
    taglia: "piccola",
    energia: "bassa",
    appartamento: "ottimo",
    bambini: "buono",
    pelo: "lungo",
    esperienzaMinima: "principiante",
    costoMensile: 120,
    descrizione: "Piccolo, bianco, coccolone. Ideale per la vita in appartamento.",
    caratteristiche: ["Mantello bianco lungo", "Molto affettuoso", "Poco impegnativo"],
    foto: "https://images.unsplash.com/photo-1583512603805-3cc6b41f3edb?w=600&q=80",
  },
  {
    slug: "barboncino",
    nome: "Barboncino",
    taglia: "media",
    energia: "media",
    appartamento: "ottimo",
    bambini: "ottimo",
    pelo: "lungo",
    esperienzaMinima: "principiante",
    costoMensile: 140,
    descrizione: "Intelligente, anallergico, elegante. Disponibile in tutte le taglie.",
    caratteristiche: ["Anallergico", "Molto intelligente", "Richiede toelettatura"],
    foto: "https://images.unsplash.com/photo-1616148195041-c7d4a55ed21d?w=600&q=80",
  },
  {
    slug: "setter-inglese",
    nome: "Setter Inglese",
    taglia: "grande",
    energia: "alta",
    appartamento: "sconsigliato",
    bambini: "ottimo",
    pelo: "lungo",
    esperienzaMinima: "intermedio",
    costoMensile: 160,
    descrizione: "Elegante, dolce, sportivo. Ha bisogno di molto spazio e movimento.",
    caratteristiche: ["Ottimo da caccia e compagnia", "Molto affettuoso", "Richiede spazio"],
    foto: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&q=80",
  },
  {
    slug: "dobermann",
    nome: "Dobermann",
    taglia: "grande",
    energia: "alta",
    appartamento: "sconsigliato",
    bambini: "buono",
    pelo: "corto",
    esperienzaMinima: "esperto",
    costoMensile: 170,
    descrizione: "Nobile, atletico, protettivo. Richiede proprietario esperto e molto movimento.",
    caratteristiche: ["Guardiano eccellente", "Molto atletico", "Richiede esperienza"],
    foto: "https://images.unsplash.com/photo-1568572933382-74d440642117?w=600&q=80",
  },
  {
    slug: "siberian-husky",
    nome: "Siberian Husky",
    taglia: "grande",
    energia: "alta",
    appartamento: "sconsigliato",
    bambini: "buono",
    pelo: "lungo",
    esperienzaMinima: "esperto",
    costoMensile: 160,
    descrizione: "Indipendente, atletico, stupendo. Non e per tutti: richiede tanto movimento.",
    caratteristiche: ["Cane da slitta", "Indipendente", "Soffre il caldo"],
    foto: "https://images.unsplash.com/photo-1605568427561-40dd23c2acea?w=600&q=80",
  },
  {
    slug: "cane-corso",
    nome: "Cane Corso",
    taglia: "gigante",
    energia: "media",
    appartamento: "sconsigliato",
    bambini: "buono",
    pelo: "corto",
    esperienzaMinima: "esperto",
    costoMensile: 200,
    descrizione: "Molosso italiano imponente e protettivo. Richiede proprietario esperto.",
    caratteristiche: ["Molto protettivo", "Grande e forte", "Solo per esperti"],
    foto: "https://images.unsplash.com/photo-1568572933382-74d440642117?w=600&q=80",
  },
  {
    slug: "meticcio",
    nome: "Meticcio da canile",
    taglia: "media",
    energia: "media",
    appartamento: "ottimo",
    bambini: "ottimo",
    pelo: "medio",
    esperienzaMinima: "principiante",
    costoMensile: 100,
    descrizione: "Ogni meticcio e unico. Adottare significa salvare una vita e avere un amico fedele.",
    caratteristiche: ["Adozione del cuore", "Grande varieta", "Spesso gia vaccinato"],
    foto: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
  },
];
