// Seed strutture ricettive pet-friendly in Italia
// Selezione editoriale di strutture note; pet-friendliness da verificare sempre
// con la struttura o tramite Booking. Affiliate link monetizzati.

import type { VacanzeSeed } from "./vacanze-types";
import { slugifyRegioneV } from "./vacanze-types";
export type { VacanzeSeed } from "./vacanze-types";
export { slugifyRegioneV, buildBookingUrl, VACANZE_TIPO_LABEL, VACANZE_TIPO_LABEL_SINGULAR, PREZZO_LABEL, PREZZO_DESCRIZIONE } from "./vacanze-types";

export function getVacanzaBySlug(slug: string): VacanzeSeed | undefined {
  return VACANZE_SEED.find((s) => s.slug === slug);
}

export function getVacanzeByRegione(regioneSlug: string): VacanzeSeed[] {
  return VACANZE_SEED.filter((s) => slugifyRegioneV(s.regione) === regioneSlug);
}

export function getAllRegioniVacanze(): string[] {
  return Array.from(new Set(VACANZE_SEED.map((s) => slugifyRegioneV(s.regione))));
}

export function unslugifyRegioneVacanze(slug: string): string | null {
  const match = Array.from(new Set(VACANZE_SEED.map((s) => s.regione))).find(
    (r) => slugifyRegioneV(r) === slug
  );
  return match || null;
}

const IMG_HOTEL = [
  "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
  "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80",
  "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80",
  "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80",
];
const IMG_AGRITURISMO = [
  "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&q=80",
  "https://images.unsplash.com/photo-1580477667995-2b94f01c9516?w=800&q=80",
  "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&q=80",
  "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80",
];
const IMG_BNB = [
  "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80",
  "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80",
  "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80",
];
const IMG_CAMPING = [
  "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&q=80",
  "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80",
  "https://images.unsplash.com/photo-1537565266759-34bbc16be345?w=800&q=80",
];
const IMG_CASA = [
  "https://images.unsplash.com/photo-1599809275671-b5942cabc7a2?w=800&q=80",
  "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
  "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
];

const pickImg = (tipo: VacanzeSeed["tipo"], i: number): string => {
  const arr =
    tipo === "hotel" ? IMG_HOTEL :
    tipo === "agriturismo" ? IMG_AGRITURISMO :
    tipo === "bnb" ? IMG_BNB :
    tipo === "camping" ? IMG_CAMPING :
    IMG_CASA;
  return arr[i % arr.length];
};

export const VACANZE_SEED: VacanzeSeed[] = [
  // === HOTEL & RESORT LUXURY ===
  { slug: "forte-village-resort-pula", nome: "Forte Village Resort", comune: "Santa Margherita di Pula", provincia: "CA", regione: "Sardegna", tipo: "hotel", descrizione: "Uno dei resort piu premiati d'Italia, sulla costa sud-ovest della Sardegna. 8 hotel, 21 ristoranti, spa thalassoterapica, accoglie animali di piccola taglia in alcune camere.", fascia: "luxury", stelle: 5, animaliAmmessi: "cane", tagliaMax: "piccola", supplementoCane: "variabile", amenities: ["Spa thalassoterapica", "Piscine olimpiche", "8 ristoranti", "Spiaggia privata", "Kids club"], img: pickImg("hotel", 0), lat: 38.9581, lng: 8.9593, bookingQuery: "Forte Village Resort Santa Margherita Pula" },
  { slug: "belmond-hotel-splendido-portofino", nome: "Belmond Hotel Splendido", comune: "Portofino", provincia: "GE", regione: "Liguria", tipo: "hotel", descrizione: "Ex monastero del XVI secolo con vista sulla baia di Portofino. Accoglie cani di piccola e media taglia su richiesta.", fascia: "luxury", stelle: 5, animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: "variabile", amenities: ["Vista baia", "Piscina riscaldata", "Spa", "Ristorante stellato", "Giardino"], img: pickImg("hotel", 1), lat: 44.3064, lng: 9.2100, bookingQuery: "Belmond Hotel Splendido Portofino" },
  { slug: "grand-hotel-tremezzo-como", nome: "Grand Hotel Tremezzo", comune: "Tremezzina", provincia: "CO", regione: "Lombardia", tipo: "hotel", descrizione: "Palazzo Liberty affacciato sul Lago di Como, con parco secolare e tre piscine. Programma pet-friendly dedicato.", fascia: "luxury", stelle: 5, animaliAmmessi: "entrambi", tagliaMax: "media", supplementoCane: "variabile", amenities: ["Vista lago", "3 piscine", "Parco secolare", "Spa", "Tenuta di 15 ettari"], img: pickImg("hotel", 2), lat: 45.9849, lng: 9.2284, bookingQuery: "Grand Hotel Tremezzo Como" },
  { slug: "splendido-bay-padenghe", nome: "Splendido Bay Luxury Spa Resort", comune: "Padenghe sul Garda", provincia: "BS", regione: "Lombardia", tipo: "hotel", descrizione: "Resort moderno sulle sponde del Garda con spa, spiaggia privata e menu dedicato per ospiti a 4 zampe.", fascia: "alto", stelle: 5, animaliAmmessi: "entrambi", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Lago di Garda", "Spa", "Spiaggia privata", "Piscina", "Menu cane"], img: pickImg("hotel", 3), lat: 45.5096, lng: 10.5064, bookingQuery: "Splendido Bay Luxury Spa Resort Padenghe" },
  { slug: "hotel-cala-di-volpe-porto-cervo", nome: "Hotel Cala di Volpe", comune: "Porto Cervo", provincia: "SS", regione: "Sardegna", tipo: "hotel", descrizione: "Icona della Costa Smeralda dal 1963. Cinque stelle lusso con baia privata e spa, accoglie piccoli cani su richiesta.", fascia: "luxury", stelle: 5, animaliAmmessi: "cane", tagliaMax: "piccola", supplementoCane: "variabile", amenities: ["Baia privata", "Spa", "Piscina olimpica", "Yacht charter", "Costa Smeralda"], img: pickImg("hotel", 0), lat: 41.0903, lng: 9.5410, bookingQuery: "Hotel Cala di Volpe Porto Cervo" },
  { slug: "capri-palace-anacapri", nome: "Capri Palace Jumeirah", comune: "Anacapri", provincia: "NA", regione: "Campania", tipo: "hotel", descrizione: "Hotel di design nell'alta Anacapri, dotato di collezione d'arte e spa unica. Accoglie cani di piccola taglia.", fascia: "luxury", stelle: 5, animaliAmmessi: "cane", tagliaMax: "piccola", supplementoCane: "variabile", amenities: ["Vista mare", "Spa esclusiva", "Ristorante stellato", "Collezione arte", "Piscina"], img: pickImg("hotel", 1), lat: 40.5557, lng: 14.2136, bookingQuery: "Capri Palace Jumeirah Anacapri" },
  { slug: "jw-marriott-venice", nome: "JW Marriott Venice Resort & Spa", comune: "Venezia", provincia: "VE", regione: "Veneto", tipo: "hotel", descrizione: "Resort su isola privata della laguna veneta, raggiungibile con navetta gratuita dal centro. Pet-friendly con amenity dedicate.", fascia: "luxury", stelle: 5, animaliAmmessi: "entrambi", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Isola privata", "Spa", "Spiaggia privata", "Navetta Venezia", "Amenity cani"], img: pickImg("hotel", 2), lat: 45.4046, lng: 12.3105, bookingQuery: "JW Marriott Venice Resort Isola delle Rose" },
  { slug: "palace-hotel-merano", nome: "Palace Hotel Merano", comune: "Merano", provincia: "BZ", regione: "Trentino-Alto Adige", tipo: "hotel", descrizione: "Storico palace termale del 1906 a Merano con spa medica Henri Chenot. Accoglie cani di tutte le taglie in camera su richiesta.", fascia: "alto", stelle: 5, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Spa medica Chenot", "Parco", "Terme", "Menu benessere", "Dog walking"], img: pickImg("hotel", 3), lat: 46.6677, lng: 11.1654, bookingQuery: "Palace Hotel Merano" },
  { slug: "villa-deste-cernobbio", nome: "Villa d'Este", comune: "Cernobbio", provincia: "CO", regione: "Lombardia", tipo: "hotel", descrizione: "Dimora storica del XVI secolo sul Lago di Como, tra le piu famose d'Europa. Accoglie cani di piccola taglia nelle suite selezionate.", fascia: "luxury", stelle: 5, animaliAmmessi: "cane", tagliaMax: "piccola", supplementoCane: "variabile", amenities: ["Parco storico 10 ettari", "Piscina sul lago", "Spa", "Campo da golf", "Ristoranti stellati"], img: pickImg("hotel", 0), lat: 45.8449, lng: 9.0798, bookingQuery: "Villa d'Este Cernobbio Como" },
  { slug: "verdura-resort-sciacca", nome: "Verdura Resort", comune: "Sciacca", provincia: "AG", regione: "Sicilia", tipo: "hotel", descrizione: "Resort del gruppo Rocco Forte sulla costa agrigentina: 230 ettari di mare, spa, golf. Pet-friendly con programma dedicato.", fascia: "luxury", stelle: 5, animaliAmmessi: "entrambi", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["230 ettari", "Spa 4000mq", "3 campi golf", "2km costa", "Bio-farm"], img: pickImg("hotel", 1), lat: 37.4742, lng: 13.1964, bookingQuery: "Verdura Resort Rocco Forte Sciacca" },
  { slug: "four-seasons-milano", nome: "Four Seasons Hotel Milano", comune: "Milano", provincia: "MI", regione: "Lombardia", tipo: "hotel", descrizione: "Ex convento del XV secolo nel Quadrilatero della Moda. Pet-friendly con amenity dedicate: ciotole, cuccia, menu cane.", fascia: "luxury", stelle: 5, animaliAmmessi: "entrambi", tagliaMax: "tutte", supplementoCane: 0, amenities: ["Ex convento storico", "Quadrilatero moda", "Menu cane", "Cuccia in camera", "Spa"], img: pickImg("hotel", 2), lat: 45.4694, lng: 9.1953, bookingQuery: "Four Seasons Hotel Milano" },
  { slug: "hotel-le-agavi-positano", nome: "Hotel Le Agavi", comune: "Positano", provincia: "SA", regione: "Campania", tipo: "hotel", descrizione: "Hotel sul promontorio di Positano con ascensore privato alla spiaggia. Accoglie cani in alcune camere su richiesta.", fascia: "alto", stelle: 5, animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: "variabile", amenities: ["Vista Costiera", "Ascensore spiaggia", "Piscina", "Ristorante sul mare", "Giardini"], img: pickImg("hotel", 3), lat: 40.6264, lng: 14.4789, bookingQuery: "Hotel Le Agavi Positano" },
  { slug: "castello-di-velona-montalcino", nome: "Castello di Velona Resort", comune: "Montalcino", provincia: "SI", regione: "Toscana", tipo: "hotel", descrizione: "Castello medievale nella Val d'Orcia trasformato in resort con spa termale e cantina Brunello. Accoglie cani di tutte le taglie.", fascia: "alto", stelle: 5, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Castello medievale", "Spa termale", "Cantina Brunello", "Val d'Orcia", "Piscine con vista"], img: pickImg("hotel", 0), lat: 43.0576, lng: 11.4903, bookingQuery: "Castello di Velona Montalcino" },
  { slug: "castello-di-casole-hotel", nome: "Belmond Castello di Casole", comune: "Casole d'Elsa", provincia: "SI", regione: "Toscana", tipo: "hotel", descrizione: "Castello del X secolo immerso in 1700 ettari di campagna toscana. Cavalli, cane e gatti benvenuti nelle suite dedicate.", fascia: "luxury", stelle: 5, animaliAmmessi: "entrambi", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["1700 ettari tenuta", "Castello X secolo", "Cavalli", "Cantina", "Spa"], img: pickImg("hotel", 1), lat: 43.3249, lng: 11.0842, bookingQuery: "Belmond Castello di Casole" },
  { slug: "grand-hotel-rimini", nome: "Grand Hotel Rimini", comune: "Rimini", provincia: "RN", regione: "Emilia-Romagna", tipo: "hotel", descrizione: "Hotel simbolo della Riviera Romagnola dal 1908, celebrato da Fellini. Accoglie cani di tutte le taglie con menu dedicato.", fascia: "alto", stelle: 5, animaliAmmessi: "entrambi", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Bagno 1", "Spiaggia privata", "Spa", "Ristorante storico", "Parco"], img: pickImg("hotel", 2), lat: 44.0727, lng: 12.5766, bookingQuery: "Grand Hotel Rimini" },
  { slug: "altafiumara-resort-calabria", nome: "Altafiumara Resort & Spa", comune: "Villa San Giovanni", provincia: "RC", regione: "Calabria", tipo: "hotel", descrizione: "Resort storico sullo Stretto di Messina con vista Sicilia. Accoglie cani in alcune camere, ampi giardini per il passeggio.", fascia: "alto", stelle: 5, animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: "variabile", amenities: ["Vista Stretto", "Spa", "Piscina", "Giardini", "Vicino Messina"], img: pickImg("hotel", 3), lat: 38.2426, lng: 15.6772, bookingQuery: "Altafiumara Resort Villa San Giovanni" },
  { slug: "abano-grand-hotel", nome: "Abano Grand Hotel", comune: "Abano Terme", provincia: "PD", regione: "Veneto", tipo: "hotel", descrizione: "Storico grand hotel termale con piscine termali, spa medica e parco secolare. Accoglie cani in alcune camere.", fascia: "alto", stelle: 5, animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: "variabile", amenities: ["Terme", "Fanghi", "Piscine termali", "Parco", "Centro medico"], img: pickImg("hotel", 0), lat: 45.3542, lng: 11.7856, bookingQuery: "Abano Grand Hotel Abano Terme" },
  { slug: "splendido-mare-portofino", nome: "Splendido Mare Portofino", comune: "Portofino", provincia: "GE", regione: "Liguria", tipo: "hotel", descrizione: "Hotel storico sulla celebre Piazzetta di Portofino, di proprieta Belmond. Accoglie cani di piccola taglia.", fascia: "alto", stelle: 4, animaliAmmessi: "cane", tagliaMax: "piccola", supplementoCane: "variabile", amenities: ["Piazzetta Portofino", "Vista mare", "Ristorante sul molo", "Suite storiche"], img: pickImg("hotel", 1), lat: 44.3017, lng: 9.2110, bookingQuery: "Belmond Splendido Mare Portofino" },
  { slug: "villa-la-massa-firenze", nome: "Villa La Massa", comune: "Bagno a Ripoli", provincia: "FI", regione: "Toscana", tipo: "hotel", descrizione: "Villa rinascimentale del XVI secolo sulle rive dell'Arno, a 15 minuti da Firenze. Ampi giardini per il passeggio con il cane.", fascia: "alto", stelle: 5, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Villa Medicea", "Riva dell'Arno", "15 min da Firenze", "Piscina", "Giardino"], img: pickImg("hotel", 2), lat: 43.7651, lng: 11.3337, bookingQuery: "Villa La Massa Firenze" },
  { slug: "palazzo-seneca-norcia", nome: "Palazzo Seneca", comune: "Norcia", provincia: "PG", regione: "Umbria", tipo: "hotel", descrizione: "Hotel nobiliare del Cinquecento nel cuore di Norcia, cucina di eccellenza con prodotti della tradizione umbra. Pet-friendly.", fascia: "alto", stelle: 4, animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: "variabile", amenities: ["Palazzo storico", "Ristorante gourmet", "Spa", "Prodotti umbri", "Centro Norcia"], img: pickImg("hotel", 3), lat: 42.7925, lng: 13.0920, bookingQuery: "Palazzo Seneca Norcia" },

  // === AGRITURISMI / MASSERIE ===
  { slug: "borgo-egnazia-savelletri", nome: "Borgo Egnazia", comune: "Savelletri di Fasano", provincia: "BR", regione: "Puglia", tipo: "agriturismo", descrizione: "Borgo pugliese contemporaneo ispirato all'architettura rurale locale. Tra i resort piu premiati d'Italia. Accoglie cani di tutte le taglie.", fascia: "luxury", stelle: 5, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Borgo tipico pugliese", "4 piscine", "Spa Vair", "6 ristoranti", "Campo da golf"], img: pickImg("agriturismo", 0), lat: 40.8745, lng: 17.3962, bookingQuery: "Borgo Egnazia Savelletri Fasano" },
  { slug: "masseria-torre-coccaro", nome: "Masseria Torre Coccaro", comune: "Savelletri di Fasano", provincia: "BR", regione: "Puglia", tipo: "agriturismo", descrizione: "Masseria del XVI secolo con ulivi secolari e giardini mediterranei. Spiaggia privata e spa, pet-friendly con menu dedicato.", fascia: "alto", stelle: 5, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Masseria XVI sec", "Ulivi secolari", "Spiaggia privata", "Spa", "Cucina tipica"], img: pickImg("agriturismo", 1), lat: 40.8730, lng: 17.4090, bookingQuery: "Masseria Torre Coccaro Savelletri" },
  { slug: "masseria-san-domenico", nome: "Masseria San Domenico", comune: "Savelletri di Fasano", provincia: "BR", regione: "Puglia", tipo: "agriturismo", descrizione: "Antica masseria fortificata del Cinquecento con campo golf, spa talassoterapica e accesso diretto al mare. Accoglie cani.", fascia: "alto", stelle: 5, animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: "variabile", amenities: ["Masseria fortificata", "Golf 18 buche", "Spa talassoterapica", "Ulivi monumentali", "Accesso mare"], img: pickImg("agriturismo", 2), lat: 40.8417, lng: 16.9136, bookingQuery: "Masseria San Domenico Fasano" },
  { slug: "masseria-il-frantoio-ostuni", nome: "Masseria Il Frantoio", comune: "Ostuni", provincia: "BR", regione: "Puglia", tipo: "agriturismo", descrizione: "Masseria biologica con un antico frantoio ipogeo del 1500, produce olio extravergine. Cani benvenuti nel parco di ulivi secolari.", fascia: "alto", stelle: 4, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Biologica certificata", "Frantoio ipogeo", "Olio extravergine", "Ulivi secolari", "Cena gourmet"], img: pickImg("agriturismo", 3), lat: 40.7585, lng: 17.5224, bookingQuery: "Masseria Il Frantoio Ostuni" },
  { slug: "tenuta-spannocchia", nome: "Tenuta di Spannocchia", comune: "Chiusdino", provincia: "SI", regione: "Toscana", tipo: "agriturismo", descrizione: "Azienda agricola biologica del 1225 nelle colline senesi. Allevamento di suini cinta senese, produzione di olio e vino. Pet-friendly.", fascia: "medio", animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Biologica 1225", "Cinta senese", "Villa medievale", "Cucina contadina", "Tenuta 1100 ettari"], img: pickImg("agriturismo", 0), lat: 43.1546, lng: 11.0842, bookingQuery: "Tenuta di Spannocchia Chiusdino" },
  { slug: "podere-dionora-montepulciano", nome: "Podere Dionora", comune: "Montepulciano", provincia: "SI", regione: "Toscana", tipo: "agriturismo", descrizione: "Boutique farm con sole 10 camere tra le vigne di Montepulciano. Vista Val d'Orcia, piscina e cucina di eccellenza.", fascia: "alto", stelle: 4, animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: "variabile", amenities: ["10 camere esclusive", "Vigne Nobile", "Vista Val d'Orcia", "Piscina", "Cucina gourmet"], img: pickImg("agriturismo", 1), lat: 43.0945, lng: 11.7827, bookingQuery: "Podere Dionora Montepulciano" },
  { slug: "borgo-santo-pietro-palazzetto", nome: "Relais Borgo Santo Pietro", comune: "Chiusdino", provincia: "SI", regione: "Toscana", tipo: "agriturismo", descrizione: "Borgo del XIII secolo trasformato in relais di lusso nel cuore delle crete senesi. Cavalli, orto biodinamico, spa.", fascia: "luxury", stelle: 5, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Borgo XIII sec", "Tenuta 150 ettari", "Cavalli", "Orto biodinamico", "Spa naturale"], img: pickImg("agriturismo", 2), lat: 43.1419, lng: 11.1268, bookingQuery: "Relais Borgo Santo Pietro Chiusdino" },
  { slug: "tenuta-poggio-ai-santi", nome: "Tenuta Poggio ai Santi", comune: "San Vincenzo", provincia: "LI", regione: "Toscana", tipo: "agriturismo", descrizione: "Relais di campagna tra mare e colline sulla Costa degli Etruschi, a pochi minuti dalla Dog Beach di San Vincenzo. Pet-friendly completo.", fascia: "alto", stelle: 4, animaliAmmessi: "entrambi", tagliaMax: "tutte", supplementoCane: 15, amenities: ["Vicino mare", "Piscina", "Dog Beach San Vincenzo", "Giardino recintato", "Cucina bio"], img: pickImg("agriturismo", 3), lat: 43.1007, lng: 10.5388, bookingQuery: "Tenuta Poggio ai Santi San Vincenzo" },
  { slug: "agriturismo-il-rigo", nome: "Agriturismo Il Rigo", comune: "San Quirico d'Orcia", provincia: "SI", regione: "Toscana", tipo: "agriturismo", descrizione: "Agriturismo familiare nel cuore della Val d'Orcia UNESCO, con cucina tradizionale e camere tra le vigne. Cani benvenuti.", fascia: "medio", animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Val d'Orcia UNESCO", "Cucina familiare", "Vigne", "Escursioni", "Pet-friendly storico"], img: pickImg("agriturismo", 0), lat: 43.0572, lng: 11.6358, bookingQuery: "Agriturismo Il Rigo San Quirico d'Orcia" },
  { slug: "masseria-susafa-polizzi", nome: "Masseria Susafa", comune: "Polizzi Generosa", provincia: "PA", regione: "Sicilia", tipo: "agriturismo", descrizione: "Masseria fortificata tra le Madonie, cucina locale e pani tradizionali. Tra i boutique agriturismi piu amati della Sicilia interna.", fascia: "alto", stelle: 4, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Parco Madonie", "Pane tradizionale", "Cucina slow food", "18 camere", "Escursioni"], img: pickImg("agriturismo", 1), lat: 37.7217, lng: 13.9343, bookingQuery: "Masseria Susafa Polizzi Generosa" },
  { slug: "il-borro-valdarno", nome: "Il Borro", comune: "San Giustino Valdarno", provincia: "AR", regione: "Toscana", tipo: "agriturismo", descrizione: "Borgo medievale di proprieta della famiglia Ferragamo, tra vigne e uliveti. Ristoranti stellati e spa. Accoglie cani.", fascia: "alto", stelle: 5, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Borgo medievale", "Ferragamo family", "Vigneto biodinamico", "Spa", "Ristorante stellato"], img: pickImg("agriturismo", 2), lat: 43.5393, lng: 11.7163, bookingQuery: "Il Borro Ferragamo Valdarno" },
  { slug: "castello-reschio-umbria", nome: "Castello di Reschio", comune: "Lisciano Niccone", provincia: "PG", regione: "Umbria", tipo: "agriturismo", descrizione: "Castello dell'anno 1000 con tenuta di 1500 ettari al confine Toscana-Umbria. Hotel di design, cavalli, spa. Pet-friendly completo.", fascia: "luxury", stelle: 5, animaliAmmessi: "entrambi", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Castello anno 1000", "1500 ettari", "50 case riservate", "Cavalli", "Spa"], img: pickImg("agriturismo", 3), lat: 43.2760, lng: 12.1987, bookingQuery: "Castello di Reschio Lisciano Niccone" },
  { slug: "borgo-pignano-volterra", nome: "Borgo Pignano", comune: "Volterra", provincia: "PI", regione: "Toscana", tipo: "agriturismo", descrizione: "Borgo del XVII secolo su 300 ettari, biologico. Piscina, spa, cooking class. Accoglie cani nelle sistemazioni indipendenti.", fascia: "alto", stelle: 5, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Borgo XVII sec", "300 ettari bio", "Piscina naturale", "Spa", "Cooking class"], img: pickImg("agriturismo", 0), lat: 43.4161, lng: 10.9636, bookingQuery: "Borgo Pignano Volterra" },
  { slug: "castelfalfi-montaione", nome: "Castelfalfi", comune: "Montaione", provincia: "FI", regione: "Toscana", tipo: "agriturismo", descrizione: "Borgo medievale su 2700 ettari tra Siena e Firenze, con 27 buche di golf, cantina e resort. Accoglie cani in alcune sistemazioni.", fascia: "alto", stelle: 4, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Borgo medievale", "Golf 27 buche", "Cantina", "Spa", "2700 ettari"], img: pickImg("agriturismo", 1), lat: 43.5474, lng: 10.8573, bookingQuery: "Castelfalfi Montaione Toscana" },
  { slug: "relais-la-sommita-ostuni", nome: "Relais La Sommita", comune: "Ostuni", provincia: "BR", regione: "Puglia", tipo: "agriturismo", descrizione: "Hotel de charme nel centro storico della Citta Bianca di Ostuni. Vista sulla valle d'Itria e ristorante stellato.", fascia: "alto", stelle: 5, animaliAmmessi: "cane", tagliaMax: "piccola", supplementoCane: "variabile", amenities: ["Citta Bianca Ostuni", "Ristorante stellato", "Vista Valle d'Itria", "Spa", "Palazzo XVI sec"], img: pickImg("agriturismo", 2), lat: 40.7343, lng: 17.5780, bookingQuery: "Relais La Sommita Ostuni" },
  { slug: "masseria-li-foggi-gallipoli", nome: "Masseria Li Foggi", comune: "Gallipoli", provincia: "LE", regione: "Puglia", tipo: "agriturismo", descrizione: "Tipica masseria salentina del XVII secolo con antica cappella, piscine e cucina regionale. Giardino per cani recintato.", fascia: "medio", stelle: 4, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Masseria XVII sec", "Piscine", "Cappella storica", "Cucina salentina", "Giardino"], img: pickImg("agriturismo", 3), lat: 40.0567, lng: 17.9964, bookingQuery: "Masseria Li Foggi Gallipoli" },
  { slug: "agriturismo-fagianaia-bolgheri", nome: "Agriturismo La Fagianaia", comune: "Bolgheri", provincia: "LI", regione: "Toscana", tipo: "agriturismo", descrizione: "Agriturismo tra i vigneti di Bolgheri DOC, vicino alla celebre strada degli ulivi. Cucina tipica e cani benvenuti.", fascia: "medio", animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Vigne Bolgheri DOC", "Cucina tipica", "Piscina", "Pet-friendly", "Cantina"], img: pickImg("agriturismo", 0), lat: 43.9066, lng: 10.7264, bookingQuery: "Agriturismo La Fagianaia Bolgheri" },

  // === B&B / BOUTIQUE ===
  { slug: "la-bandita-townhouse-pienza", nome: "La Bandita Townhouse", comune: "Pienza", provincia: "SI", regione: "Toscana", tipo: "bnb", descrizione: "Boutique townhouse nel centro storico di Pienza, 12 camere esclusive e wine bar. Val d'Orcia a portata di mano. Pet-friendly.", fascia: "alto", stelle: 4, animaliAmmessi: "cane", tagliaMax: "piccola", supplementoCane: "variabile", amenities: ["Centro storico Pienza", "12 camere", "Wine bar", "Val d'Orcia", "Concierge"], img: pickImg("bnb", 0), lat: 43.0765, lng: 11.6789, bookingQuery: "La Bandita Townhouse Pienza" },
  { slug: "monastero-santa-rosa-conca-marini", nome: "Monastero Santa Rosa Hotel & Spa", comune: "Conca dei Marini", provincia: "SA", regione: "Campania", tipo: "bnb", descrizione: "Ex monastero del XVII secolo sulla Costiera Amalfitana, 20 camere con vista mare e spa. Boutique unico in Italia.", fascia: "luxury", stelle: 5, animaliAmmessi: "cane", tagliaMax: "piccola", supplementoCane: "variabile", amenities: ["Ex monastero XVII sec", "Costiera Amalfitana", "Spa", "20 camere esclusive", "Vista mare"], img: pickImg("bnb", 1), lat: 40.6176, lng: 14.5725, bookingQuery: "Monastero Santa Rosa Conca dei Marini" },
  { slug: "palazzo-monti-brescia", nome: "Palazzo Monti", comune: "Brescia", provincia: "BS", regione: "Lombardia", tipo: "bnb", descrizione: "Palazzo storico del XIII secolo nel centro di Brescia, residenza d'artista e boutique B&B con affreschi originali. Pet-friendly.", fascia: "medio", animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: 0, amenities: ["Palazzo XIII sec", "Affreschi originali", "Artist residency", "Centro Brescia", "Arte"], img: pickImg("bnb", 2), lat: 45.4058, lng: 10.3909, bookingQuery: "Palazzo Monti Brescia" },
  { slug: "villa-cattani-stuart-pesaro", nome: "Villa Cattani Stuart", comune: "Pesaro", provincia: "PU", regione: "Marche", tipo: "bnb", descrizione: "Villa storica del XVII secolo alle porte di Pesaro, circondata dal parco San Bartolo. Cani benvenuti nel parco privato.", fascia: "medio", stelle: 4, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Villa XVII sec", "Parco privato", "Piscina", "Parco San Bartolo", "Spiaggia vicina"], img: pickImg("bnb", 0), lat: 43.8717, lng: 12.9429, bookingQuery: "Villa Cattani Stuart Pesaro" },
  { slug: "relais-villa-san-martino-martina", nome: "Relais Villa San Martino", comune: "Martina Franca", provincia: "TA", regione: "Puglia", tipo: "bnb", descrizione: "Masseria boutique alle porte di Martina Franca, nella Valle d'Itria dei trulli. Piscina, ristorante e camere curate.", fascia: "alto", stelle: 5, animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: "variabile", amenities: ["Valle d'Itria", "Piscina", "Ristorante", "Trulli vicini", "Spa"], img: pickImg("bnb", 1), lat: 40.7031, lng: 17.3365, bookingQuery: "Relais Villa San Martino Martina Franca" },
  { slug: "locanda-sant-agostino-pietrasanta", nome: "Locanda Sant'Agostino", comune: "Pietrasanta", provincia: "LU", regione: "Toscana", tipo: "bnb", descrizione: "Locanda storica nel centro di Pietrasanta, cittadina versiliese famosa per l'arte e il marmo. Pet-friendly con giardino.", fascia: "medio", animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: "variabile", amenities: ["Centro Pietrasanta", "Versilia", "Giardino", "Cani benvenuti", "Arte"], img: pickImg("bnb", 2), lat: 43.9601, lng: 10.2305, bookingQuery: "Locanda Sant'Agostino Pietrasanta" },

  // === CAMPING / GLAMPING / VILLAGE ===
  { slug: "union-lido-cavallino", nome: "Union Lido Park & Resort", comune: "Cavallino-Treporti", provincia: "VE", regione: "Veneto", tipo: "camping", descrizione: "Uno dei campeggi piu grandi d'Europa sul litorale veneziano, 60 ettari con piscine, spiaggia privata e zone pet dedicate.", fascia: "medio", animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["60 ettari", "Parco acquatico", "Spiaggia 1.2km", "Area cani dedicata", "Piazzole pet"], img: pickImg("camping", 0), lat: 45.4792, lng: 12.5153, bookingQuery: "Union Lido Cavallino Treporti" },
  { slug: "marina-di-venezia-camping", nome: "Camping Marina di Venezia", comune: "Cavallino-Treporti", provincia: "VE", regione: "Veneto", tipo: "camping", descrizione: "Campeggio 5 stelle con spiaggia privata di 1km, parco acquatico e area dog beach. Tra i piu premiati del Nord Adriatico.", fascia: "medio", stelle: 5, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["5 stelle", "Parco acquatico", "Dog beach", "1km spiaggia", "Piazzole pet"], img: pickImg("camping", 1), lat: 45.4363, lng: 12.4410, bookingQuery: "Camping Marina di Venezia Cavallino" },
  { slug: "ca-pasquali-village", nome: "Ca' Pasquali Village", comune: "Cavallino-Treporti", provincia: "VE", regione: "Veneto", tipo: "camping", descrizione: "Village bungalow-camping nella pineta del Cavallino, a 100m dal mare. Area cani e dog beach nelle vicinanze.", fascia: "medio", stelle: 5, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Pineta", "100m dal mare", "Piscine", "Bungalow pet", "Area cani"], img: pickImg("camping", 2), lat: 45.4619, lng: 12.4876, bookingQuery: "Ca Pasquali Village Cavallino" },
  { slug: "fabulous-village-roma", nome: "Fabulous Camping Village", comune: "Roma", provincia: "RM", regione: "Lazio", tipo: "camping", descrizione: "Campeggio a Lido di Ostia, base perfetta per visitare Roma con il cane. Piazzole pet-friendly e navetta.", fascia: "medio", stelle: 4, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Lido di Ostia", "Navetta Roma", "Piazzole pet", "Piscina", "Vicino spiaggia"], img: pickImg("camping", 0), lat: 41.7353, lng: 12.2766, bookingQuery: "Fabulous Camping Village Ostia Roma" },
  { slug: "park-albatros-san-vincenzo", nome: "Park Albatros Village", comune: "San Vincenzo", provincia: "LI", regione: "Toscana", tipo: "camping", descrizione: "Village 5 stelle sulla Costa degli Etruschi con parco acquatico, accesso diretto alla pineta e dog beach di San Vincenzo.", fascia: "medio", stelle: 5, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Parco acquatico", "Pineta", "Dog beach vicina", "Animazione", "Bungalow pet"], img: pickImg("camping", 1), lat: 43.0280, lng: 10.5365, bookingQuery: "Park Albatros Village San Vincenzo" },
  { slug: "argentario-camping-village", nome: "Argentario Camping Village", comune: "Orbetello", provincia: "GR", regione: "Toscana", tipo: "camping", descrizione: "Camping e bungalow village sulla tombola di Giannella, Argentario. Spiaggia riservata e area cani nella pineta mediterranea.", fascia: "medio", stelle: 4, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Argentario", "Tombolo di Giannella", "Spiaggia privata", "Pineta", "Area cani"], img: pickImg("camping", 2), lat: 42.4956, lng: 11.1932, bookingQuery: "Argentario Camping Village Orbetello" },
  { slug: "santapomata-camping", nome: "Camping Village Santapomata", comune: "Castiglione della Pescaia", provincia: "GR", regione: "Toscana", tipo: "camping", descrizione: "Camping Village nella pineta di Castiglione della Pescaia, accesso diretto alla spiaggia. Maremma Toscana, ambiente familiare.", fascia: "medio", stelle: 4, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Castiglione Pescaia", "Pineta", "Accesso spiaggia", "Maremma", "Area cani"], img: pickImg("camping", 0), lat: 42.7639, lng: 10.8791, bookingQuery: "Camping Village Santapomata Castiglione" },
  { slug: "baia-blu-tortuga-aglientu", nome: "Baia Blu La Tortuga", comune: "Aglientu", provincia: "SS", regione: "Sardegna", tipo: "camping", descrizione: "Camping Village nella costa della Gallura, a pochi metri dalla spiaggia di Vignola Mare. Pineta, piazzole pet e bungalow.", fascia: "medio", stelle: 4, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Gallura", "Vignola Mare", "Pineta", "Bungalow pet", "Piazzole pet"], img: pickImg("camping", 1), lat: 41.1258, lng: 9.0677, bookingQuery: "Baia Blu La Tortuga Aglientu" },
  { slug: "tiliguerta-camping-muravera", nome: "Camping Tiliguerta", comune: "Muravera", provincia: "SU", regione: "Sardegna", tipo: "camping", descrizione: "Camping sulla celebre Costa Rei, accesso diretto alla spiaggia con la Tiliguerta Dog Beach. Bungalow e piazzole pet-friendly.", fascia: "medio", stelle: 3, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Costa Rei", "Tiliguerta Dog Beach", "Pineta", "Bungalow pet", "Spiaggia privata"], img: pickImg("camping", 2), lat: 39.2909, lng: 9.6003, bookingQuery: "Camping Tiliguerta Costa Rei Muravera" },
  { slug: "europa-silvella-garda", nome: "Camping Village Europa Silvella", comune: "San Felice del Benaco", provincia: "BS", regione: "Lombardia", tipo: "camping", descrizione: "Village 4 stelle sulla sponda bresciana del Lago di Garda, con 4 piscine, parco acquatico e area cani attrezzata.", fascia: "medio", stelle: 4, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Lago di Garda", "4 piscine", "Parco acquatico", "Area cani", "Spiaggia privata"], img: pickImg("camping", 0), lat: 45.5895, lng: 10.5517, bookingQuery: "Europa Silvella San Felice Garda" },
  { slug: "torre-rinalda-lecce", nome: "Camping Torre Rinalda", comune: "Lecce", provincia: "LE", regione: "Puglia", tipo: "camping", descrizione: "Camping Village sulla costa adriatica salentina, piazzole in pineta e accesso diretto al mare. Cani benvenuti.", fascia: "medio", stelle: 4, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Costa adriatica Salento", "Pineta", "Accesso mare", "Bungalow pet", "Piscina"], img: pickImg("camping", 1), lat: 40.4831, lng: 18.1472, bookingQuery: "Camping Torre Rinalda Lecce" },
  { slug: "camping-la-pineta-sicilia", nome: "Camping La Pineta sul Mare", comune: "Calatabiano", provincia: "CT", regione: "Sicilia", tipo: "camping", descrizione: "Camping sulla costa ionica catanese tra mare e Etna. Pineta naturale, piazzole e bungalow pet-friendly. Vicino Taormina.", fascia: "economico", stelle: 3, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Pineta sul mare", "Vicino Taormina", "Vista Etna", "Piazzole pet", "Bungalow"], img: pickImg("camping", 2), lat: 37.8224, lng: 15.2276, bookingQuery: "Camping La Pineta Calatabiano Sicilia" },
  { slug: "camping-baia-azzurra-scarlino", nome: "Camping Baia Azzurra", comune: "Scarlino", provincia: "GR", regione: "Toscana", tipo: "camping", descrizione: "Camping sulla costa maremmana, a pochi passi da Cala Violina. Macchia mediterranea e spiaggia bandiera blu.", fascia: "medio", stelle: 4, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Cala Violina vicina", "Maremma", "Bandiera blu", "Bungalow pet", "Pineta"], img: pickImg("camping", 0), lat: 42.9074, lng: 10.8520, bookingQuery: "Camping Baia Azzurra Scarlino" },
  { slug: "camping-spiaggia-lunga-vieste", nome: "Camping Spiaggia Lunga", comune: "Vieste", provincia: "FG", regione: "Puglia", tipo: "camping", descrizione: "Campeggio nel Parco Nazionale del Gargano, sulla spiaggia di Scialmarino. Pineta naturale e bungalow pet-friendly.", fascia: "medio", stelle: 3, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Parco Gargano", "Spiaggia Scialmarino", "Pineta", "Bungalow pet", "Accesso mare"], img: pickImg("camping", 1), lat: 41.9199, lng: 16.1106, bookingQuery: "Camping Spiaggia Lunga Vieste" },

  // === CASE VACANZA / DIMORE ===
  { slug: "hotel-romazzino-porto-cervo", nome: "Hotel Romazzino", comune: "Porto Cervo", provincia: "SS", regione: "Sardegna", tipo: "casa_vacanza", descrizione: "Hotel icona della Costa Smeralda dal 1965, con baia privata e campi da tennis. Accoglie cani di piccola taglia su richiesta.", fascia: "luxury", stelle: 5, animaliAmmessi: "cane", tagliaMax: "piccola", supplementoCane: "variabile", amenities: ["Costa Smeralda", "Baia privata", "Tennis", "Piscina", "Spa"], img: pickImg("casa_vacanza", 0), lat: 41.0992, lng: 9.5643, bookingQuery: "Hotel Romazzino Porto Cervo" },
  { slug: "falconara-resort-butera", nome: "Falconara Charming House Resort", comune: "Butera", provincia: "CL", regione: "Sicilia", tipo: "casa_vacanza", descrizione: "Castello medievale sul mare tra Gela e Agrigento, unico nel suo genere in Sicilia. Ampi giardini e accoglie cani.", fascia: "alto", stelle: 4, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Castello medievale", "Spiaggia privata", "Giardino storico", "Cucina siciliana", "Stretto di Sicilia"], img: pickImg("casa_vacanza", 1), lat: 37.1102, lng: 14.0530, bookingQuery: "Falconara Charming House Butera Sicilia" },
  { slug: "hotel-paradise-pantelleria", nome: "Hotel Paradise Pantelleria", comune: "Pantelleria", provincia: "TP", regione: "Sicilia", tipo: "casa_vacanza", descrizione: "Hotel boutique sull'isola di Pantelleria, dove il cane puo vivere il fascino dei dammusi e delle cale vulcaniche.", fascia: "medio", stelle: 3, animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: "variabile", amenities: ["Isola Pantelleria", "Dammusi", "Cale vulcaniche", "Cucina mediterranea", "Pet-friendly"], img: pickImg("casa_vacanza", 2), lat: 36.8378, lng: 11.9965, bookingQuery: "Hotel Paradise Pantelleria" },

  // === CALABRIA (aggiunte) ===
  { slug: "capovaticano-resort-tropea", nome: "Capovaticano Resort Thalasso & Spa", comune: "Ricadi", provincia: "VV", regione: "Calabria", tipo: "hotel", descrizione: "Resort 4 stelle sulla Costa degli Dei con thalasso spa, piscine e spiaggia privata. Accoglie cani di piccola e media taglia.", fascia: "alto", stelle: 4, animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: "variabile", amenities: ["Costa degli Dei", "Thalasso spa", "Spiaggia privata", "Piscine", "Vista Stromboli"], img: pickImg("hotel", 0), lat: 38.6151, lng: 15.8301, bookingQuery: "Capovaticano Resort Ricadi" },
  { slug: "praia-art-resort-le-castella", nome: "Praia Art Resort", comune: "Isola di Capo Rizzuto", provincia: "KR", regione: "Calabria", tipo: "hotel", descrizione: "Boutique art resort sulla costa ionica crotonese, nel Parco Marino di Capo Rizzuto. Architettura mediterranea contemporanea.", fascia: "alto", stelle: 5, animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: "variabile", amenities: ["Parco Marino", "Spiaggia privata", "Spa", "Architettura design", "Ristorante gourmet"], img: pickImg("hotel", 1), lat: 38.9083, lng: 17.0475, bookingQuery: "Praia Art Resort Le Castella" },

  // === MARCHE (aggiunte) ===
  { slug: "borgo-dei-conti-villagrande", nome: "Borgo dei Conti Resort", comune: "Monte Cerignone", provincia: "PU", regione: "Marche", tipo: "agriturismo", descrizione: "Antico borgo trasformato in resort di charme nell'entroterra marchigiano. Ideale per chi cerca natura e tranquillita'.", fascia: "medio", animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Borgo storico", "Piscina", "Ristorante tipico", "Entroterra", "Escursioni"], img: pickImg("agriturismo", 0), lat: 43.8489, lng: 12.4222, bookingQuery: "Borgo dei Conti Resort Monte Cerignone" },
  { slug: "hotel-villa-amalia-ancona", nome: "Hotel Villa Amalia", comune: "Falconara Marittima", provincia: "AN", regione: "Marche", tipo: "hotel", descrizione: "Hotel 4 stelle sul mare di Falconara, a pochi km da Ancona. Vicino al Parco del Conero.", fascia: "medio", stelle: 4, animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: "variabile", amenities: ["Sul mare", "Vicino Conero", "Ristorante", "Parco privato"], img: pickImg("hotel", 1), lat: 43.6279, lng: 13.4016, bookingQuery: "Hotel Villa Amalia Falconara" },
  { slug: "green-garden-camping-senigallia", nome: "Camping Green Garden Village", comune: "Senigallia", provincia: "AN", regione: "Marche", tipo: "camping", descrizione: "Camping village a Senigallia, accesso diretto alla celebre spiaggia di velluto. Area cani e piazzole ombreggiate.", fascia: "medio", animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Spiaggia di velluto", "Piazzole ombreggiate", "Area cani", "Piscina"], img: pickImg("camping", 0), lat: 43.7022, lng: 13.2459, bookingQuery: "Camping Green Garden Senigallia" },

  // === ABRUZZO ===
  { slug: "villaggio-eden-pineto", nome: "Villaggio Turistico Eden", comune: "Pineto", provincia: "TE", regione: "Abruzzo", tipo: "camping", descrizione: "Villaggio turistico sulla costa teramana, immerso in una pineta naturale. Bungalow e piazzole pet-friendly.", fascia: "medio", animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Pineta naturale", "Accesso mare", "Bungalow pet", "Piscina"], img: pickImg("camping", 1), lat: 42.6133, lng: 14.0647, bookingQuery: "Villaggio Eden Pineto" },
  { slug: "golf-hotel-punta-aderci", nome: "Golf Hotel Punta Aderci", comune: "Vasto", provincia: "CH", regione: "Abruzzo", tipo: "hotel", descrizione: "Resort con campo da golf sulla Costa dei Trabocchi, vicino alla Riserva di Punta Aderci. Cani benvenuti.", fascia: "medio", stelle: 4, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Campo golf", "Costa Trabocchi", "Riserva Punta Aderci", "Piscina"], img: pickImg("hotel", 2), lat: 42.1145, lng: 14.6916, bookingQuery: "Golf Hotel Punta Aderci Vasto" },
  { slug: "le-casette-di-jemma-scanno", nome: "Le Casette di Jemma", comune: "Scanno", provincia: "AQ", regione: "Abruzzo", tipo: "casa_vacanza", descrizione: "Case vacanza nel borgo medievale di Scanno, nel Parco Nazionale d'Abruzzo. Ideale per escursioni in montagna col cane.", fascia: "medio", animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Borgo medievale", "Parco Nazionale Abruzzo", "Montagna", "Lago di Scanno"], img: pickImg("casa_vacanza", 0), lat: 41.9042, lng: 13.8827, bookingQuery: "Le Casette di Jemma Scanno" },
  { slug: "sextantio-albergo-diffuso", nome: "Sextantio Albergo Diffuso", comune: "Santo Stefano di Sessanio", provincia: "AQ", regione: "Abruzzo", tipo: "bnb", descrizione: "Il primo albergo diffuso d'Italia, nel borgo medievale di Santo Stefano di Sessanio nel Parco del Gran Sasso. Esperienza unica.", fascia: "alto", stelle: 4, animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: "variabile", amenities: ["Albergo diffuso", "Gran Sasso", "Borgo medievale", "Cucina tradizionale", "Esperienza slow"], img: pickImg("bnb", 0), lat: 42.3561, lng: 13.6476, bookingQuery: "Sextantio Santo Stefano di Sessanio" },

  // === MOLISE ===
  { slug: "costa-verde-camping-molise", nome: "Costa Verde Camping Village", comune: "Montenero di Bisaccia", provincia: "CB", regione: "Molise", tipo: "camping", descrizione: "Camping village sulla costa molisana, vicino al confine abruzzese. Pineta e accesso mare, bungalow pet-friendly.", fascia: "economico", animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Pineta", "Accesso mare", "Bungalow pet", "Tranquillita"], img: pickImg("camping", 2), lat: 42.0303, lng: 14.7694, bookingQuery: "Costa Verde Camping Montenero di Bisaccia" },
  { slug: "santavenere-termoli-bnb", nome: "Santavenere B&B Termoli", comune: "Termoli", provincia: "CB", regione: "Molise", tipo: "bnb", descrizione: "B&B boutique a Termoli, nel cuore del borgo antico affacciato sul mare. Ambiente familiare, cani benvenuti.", fascia: "economico", animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Borgo antico", "Vicino mare", "Terrazza", "Familiare"], img: pickImg("bnb", 1), lat: 42.0000, lng: 14.9968, bookingQuery: "B&B Termoli borgo antico" },

  // === FRIULI-VENEZIA GIULIA ===
  { slug: "falkensteiner-jesolo-lignano", nome: "Falkensteiner Hotel Park Lignano", comune: "Lignano Sabbiadoro", provincia: "UD", regione: "Friuli-Venezia Giulia", tipo: "hotel", descrizione: "Hotel 4 stelle superior sulla Riviera friulana, con spa e piscine. Accoglie cani con policy pet dedicata.", fascia: "alto", stelle: 4, animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: "variabile", amenities: ["Spa Acquapura", "Piscine", "Kids club", "Pet program", "Spiaggia privata"], img: pickImg("hotel", 3), lat: 45.6824, lng: 13.1092, bookingQuery: "Falkensteiner Hotel Park Lignano" },
  { slug: "camping-pino-mare-lignano", nome: "Camping Pino Mare", comune: "Lignano Riviera", provincia: "UD", regione: "Friuli-Venezia Giulia", tipo: "camping", descrizione: "Camping nella pineta di Lignano Riviera, con bungalow e piazzole. Area cani e accesso diretto al mare.", fascia: "medio", animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Pineta Lignano", "Accesso mare", "Bungalow pet", "Area cani"], img: pickImg("camping", 0), lat: 45.6496, lng: 13.0972, bookingQuery: "Camping Pino Mare Lignano" },
  { slug: "grand-hotel-astoria-grado", nome: "Grand Hotel Astoria", comune: "Grado", provincia: "GO", regione: "Friuli-Venezia Giulia", tipo: "hotel", descrizione: "Storico grand hotel a Grado, l'isola UNESCO del Friuli-Venezia Giulia. Piscina termale e accesso diretto al centro storico.", fascia: "alto", stelle: 4, animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: "variabile", amenities: ["Grado centro storico", "Piscina termale", "Spa", "Cucina regionale"], img: pickImg("hotel", 0), lat: 45.6759, lng: 13.3874, bookingQuery: "Grand Hotel Astoria Grado" },
  { slug: "camping-europa-grado", nome: "Camping Europa Grado", comune: "Grado", provincia: "GO", regione: "Friuli-Venezia Giulia", tipo: "camping", descrizione: "Camping a Grado Pineta, tra spiaggia e bosco. Bungalow e piazzole con piazzole pet, accesso diretto al mare.", fascia: "medio", animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Grado Pineta", "Accesso mare", "Bungalow pet", "Piscina"], img: pickImg("camping", 1), lat: 45.6952, lng: 13.4575, bookingQuery: "Camping Europa Grado" },

  // === BASILICATA (aggiuntive) ===
  { slug: "la-mola-matera", nome: "La Mola B&B Matera", comune: "Matera", provincia: "MT", regione: "Basilicata", tipo: "bnb", descrizione: "B&B nel cuore dei Sassi di Matera, patrimonio UNESCO. Vivere l'esperienza dei sassi accompagnati dal proprio cane.", fascia: "medio", animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: "variabile", amenities: ["Sassi UNESCO", "Centro storico", "Esperienza unica", "Colazione tipica"], img: pickImg("bnb", 2), lat: 40.4476, lng: 16.4736, bookingQuery: "B&B Matera Sassi centro storico" },
  { slug: "hotel-villa-del-mare-maratea", nome: "Villa del Mare Maratea", comune: "Maratea", provincia: "PZ", regione: "Basilicata", tipo: "hotel", descrizione: "Hotel sul lungomare di Maratea, con vista sul Golfo di Policastro. Piscine, spa e accesso al mare.", fascia: "medio", stelle: 4, animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: "variabile", amenities: ["Vista Golfo Policastro", "Piscine", "Spa", "Accesso mare"], img: pickImg("hotel", 1), lat: 40.0312, lng: 15.6756, bookingQuery: "Villa del Mare Maratea hotel" },

  // === LAZIO (aggiuntive) ===
  { slug: "park-hotel-marlin-sabaudia", nome: "Park Hotel Marlin", comune: "Sabaudia", provincia: "LT", regione: "Lazio", tipo: "hotel", descrizione: "Hotel 4 stelle nel Parco Nazionale del Circeo, vicino al lago di Sabaudia e alle dune. Cani benvenuti.", fascia: "medio", stelle: 4, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Parco Circeo", "Lago Sabaudia", "Dune sabbiose", "Piscina"], img: pickImg("hotel", 2), lat: 41.3016, lng: 13.0259, bookingQuery: "Park Hotel Marlin Sabaudia" },
  { slug: "circeo-park-hotel", nome: "Circeo Park Hotel", comune: "San Felice Circeo", provincia: "LT", regione: "Lazio", tipo: "hotel", descrizione: "Hotel storico ai piedi del Monte Circeo, nel parco nazionale. Vicino a Torre Paola e alle dune.", fascia: "medio", stelle: 4, animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: "variabile", amenities: ["Monte Circeo", "Parco Nazionale", "Piscina", "Vicino mare"], img: pickImg("hotel", 3), lat: 41.2326, lng: 13.0894, bookingQuery: "Circeo Park Hotel San Felice Circeo" },
  { slug: "il-mulino-acquafredda", nome: "Il Mulino di Acquafredda", comune: "Fiuggi", provincia: "FR", regione: "Lazio", tipo: "agriturismo", descrizione: "Agriturismo nell'entroterra laziale, in un antico mulino ristrutturato. Perfetto per chi cerca tranquillita' e natura.", fascia: "economico", animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Antico mulino", "Natura", "Cucina tipica", "Terme Fiuggi vicine"], img: pickImg("agriturismo", 1), lat: 41.7986, lng: 13.2205, bookingQuery: "Agriturismo Il Mulino Fiuggi" },

  // === LIGURIA (aggiuntive) ===
  { slug: "grand-hotel-miramare-santa-margherita", nome: "Grand Hotel Miramare", comune: "Santa Margherita Ligure", provincia: "GE", regione: "Liguria", tipo: "hotel", descrizione: "Storico 5 stelle del 1903 sul Tigullio, con parco secolare e piscina sul mare. Accoglie cani di piccola taglia.", fascia: "luxury", stelle: 5, animaliAmmessi: "cane", tagliaMax: "piccola", supplementoCane: "variabile", amenities: ["Belle Epoque 1903", "Parco secolare", "Piscina sul mare", "Spa", "Tigullio"], img: pickImg("hotel", 0), lat: 44.3278, lng: 9.2150, bookingQuery: "Grand Hotel Miramare Santa Margherita Ligure" },
  { slug: "camping-fossalta-dolceacqua", nome: "Camping Fossalta", comune: "Bordighera", provincia: "IM", regione: "Liguria", tipo: "camping", descrizione: "Camping sulla Riviera di Ponente ligure, vicino al confine francese. Piazzole pet-friendly e accesso mare.", fascia: "economico", animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Riviera Ponente", "Accesso mare", "Piazzole pet", "Vicino Francia"], img: pickImg("camping", 2), lat: 43.7851, lng: 7.6591, bookingQuery: "Camping Fossalta Bordighera" },
  { slug: "hotel-bristol-bordighera", nome: "Hotel Bristol Bordighera", comune: "Bordighera", provincia: "IM", regione: "Liguria", tipo: "hotel", descrizione: "Hotel belle epoque a Bordighera, citta' delle palme. Tradizione dell'ospitalita' ligure, giardini e vista mare.", fascia: "medio", stelle: 4, animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: "variabile", amenities: ["Belle Epoque", "Giardini", "Vista mare", "Centro Bordighera"], img: pickImg("hotel", 1), lat: 43.7851, lng: 7.6591, bookingQuery: "Hotel Bristol Bordighera" },

  // === TRENTINO-ALTO ADIGE ===
  { slug: "hotel-cavallino-bianco-ortisei", nome: "Hotel Cavallino Bianco", comune: "Ortisei", provincia: "BZ", regione: "Trentino-Alto Adige", tipo: "hotel", descrizione: "Family luxury resort 5 stelle nel cuore della Val Gardena, ai piedi del massiccio del Sella. Kids paradise e pet-friendly.", fascia: "luxury", stelle: 5, animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: "variabile", amenities: ["Val Gardena", "Family resort", "Spa", "Kids world", "Dolomiti UNESCO"], img: pickImg("hotel", 2), lat: 46.5741, lng: 11.6707, bookingQuery: "Hotel Cavallino Bianco Ortisei" },
  { slug: "quellenhof-see-lodge-passiria", nome: "Quellenhof See Lodge", comune: "San Martino in Passiria", provincia: "BZ", regione: "Trentino-Alto Adige", tipo: "hotel", descrizione: "Design resort nella Val Passiria con lago privato e spa. Accoglie cani con programma dedicato.", fascia: "luxury", stelle: 5, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Lago privato", "Spa", "Design resort", "Val Passiria", "Escursioni"], img: pickImg("hotel", 3), lat: 46.7839, lng: 11.2268, bookingQuery: "Quellenhof See Lodge San Martino in Passiria" },
  { slug: "adler-mountain-lodge-alpe-siusi", nome: "Adler Mountain Lodge", comune: "Alpe di Siusi", provincia: "BZ", regione: "Trentino-Alto Adige", tipo: "hotel", descrizione: "Mountain lodge di lusso sull'Alpe di Siusi, il piu' grande altipiano d'Europa. Ski-in/ski-out in inverno, escursioni in estate.", fascia: "luxury", stelle: 5, animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Alpe di Siusi", "Ski-in/out", "Spa", "Escursioni", "Dolomiti"], img: pickImg("hotel", 0), lat: 46.5311, lng: 11.6247, bookingQuery: "Adler Mountain Lodge Alpe di Siusi" },

  // === PIEMONTE ===
  { slug: "camping-verbano-arolo", nome: "Camping Verbano", comune: "Leggiuno", provincia: "VA", regione: "Piemonte", tipo: "camping", descrizione: "Camping sul Lago Maggiore, nel parco del Campo dei Fiori. Piazzole pet-friendly con vista lago.", fascia: "economico", animaliAmmessi: "cane", tagliaMax: "tutte", supplementoCane: "variabile", amenities: ["Lago Maggiore", "Vista lago", "Piazzole pet", "Escursioni"], img: pickImg("camping", 0), lat: 45.8754, lng: 8.6205, bookingQuery: "Camping Verbano Leggiuno" },
  { slug: "hotel-astoria-stresa", nome: "Hotel Astoria Stresa", comune: "Stresa", provincia: "VB", regione: "Piemonte", tipo: "hotel", descrizione: "Hotel 4 stelle sul lungolago di Stresa, affacciato sulle Isole Borromee. Tradizione dell'ospitalita' del Lago Maggiore.", fascia: "medio", stelle: 4, animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: "variabile", amenities: ["Lungolago Stresa", "Vista Borromee", "Spa", "Ristorante"], img: pickImg("hotel", 1), lat: 45.8852, lng: 8.5363, bookingQuery: "Hotel Astoria Stresa" },
  { slug: "relais-sant-uffizio-cioccaro", nome: "Relais Sant'Uffizio", comune: "Penango", provincia: "AT", regione: "Piemonte", tipo: "agriturismo", descrizione: "Ex convento del XVI secolo trasformato in resort di lusso nel Monferrato patrimonio UNESCO. Tra vigne e noccioleti.", fascia: "alto", stelle: 5, animaliAmmessi: "cane", tagliaMax: "media", supplementoCane: "variabile", amenities: ["Ex convento XVI sec", "Monferrato UNESCO", "Vigne", "Spa", "Cucina gourmet"], img: pickImg("agriturismo", 2), lat: 45.0270, lng: 8.2772, bookingQuery: "Relais Sant'Uffizio Penango Monferrato" },
];
